// All player-facing slot text (English + Spanish). Namespace: 'slots'.
import { i18n } from '../../core/i18n.js';

i18n.register('slots', {
  en: {
    'btn.cashout': 'CASH\nOUT',
    'btn.help': 'PAYS',
    'btn.lines': 'LINES',
    'btn.betminus': 'BET –',
    'btn.betplus': 'BET +',
    'btn.maxbet': 'MAX\nBET',
    'btn.service': 'SERVICE',
    'btn.betone': 'BET\nONE',
    'btn.betmax': 'BET\nMAX',
    'btn.spin': 'SPIN',
    'btn.repeat': 'SPIN',
    'club.line1': 'SILVERLODE CLUB',
    'club.line2': 'INSERT CARD',

    'screen.credit': 'CREDIT',
    'screen.bet': 'BET',
    'screen.win': 'WIN',
    'screen.paid': 'PAID',
    'screen.lines': '{n} LINES × {b}',
    'screen.ways': '243 WAYS × {b}',
    'screen.insert': 'INSERT BILL OR TICKET',
    'screen.press': 'PRESS SPIN TO PLAY',
    'screen.goodLuck': 'GOOD LUCK!',
    'screen.noCredit': 'INSERT MORE CREDITS',
    'screen.linePays': 'LINE {n} PAYS {amt}',
    'screen.waysPays': '{sym} × {ways} WAYS PAYS {amt}',
    'screen.scatterPays': 'SCATTER PAYS {amt}',
    'screen.totalWin': 'TOTAL WIN {amt}',
    'screen.free': 'FREE GAMES',
    'screen.freeOf': 'FREE GAME {i} OF {n}',
    'screen.freeWon': '{n} FREE GAMES!',
    'screen.freeMore': '+{n} FREE GAMES',
    'screen.freeTotal': 'FREE GAMES WIN',
    'screen.sticky': 'STICKY WILDS',
    'screen.expand': 'SAUCER WILDS EXPAND',
    'screen.hold': 'HOLD & SPIN',
    'screen.respins': 'SPINS LEFT',
    'screen.holdTotal': 'PEARLS PAY',
    'screen.bigWin': 'BIG WIN',
    'screen.hugeWin': 'HUGE WIN',
    'screen.megaWin': 'MEGA WIN',
    'screen.jackpot': 'JACKPOT',
    'screen.handpay': 'HAND PAY',
    'screen.callAttendant': 'CALL ATTENDANT',
    'screen.handpayAmt': 'JACKPOT {amt} — PLEASE WAIT',
    'screen.ticket': 'PRINTING TICKET {amt}',
    'screen.take': 'TAKE TICKET',
    'screen.cashedOut': 'CASHED OUT {amt}',
    'screen.paytable': 'PAYTABLE',
    'screen.payHelpLines': 'Wins pay left to right on played lines. Wild substitutes for all but scatter.',
    'screen.payHelpWays': '243 ways: symbols pay on adjacent reels from the left. Saucer wilds (reels 2–4) expand.',
    'screen.payHelpWest': '3+ wanted posters anywhere: 8 / 12 / 20 free games. Wilds stick for the whole feature.',
    'screen.payHelpSpace': '3 planets: 10 free games. Each expanded saucer reel multiplies wins.',
    'screen.payHelpDragon': '6+ flaming pearls: HOLD & SPIN. 3 ingots: 8 free games. Fill all 15 for the MAJOR.',
    'screen.touchToClose': 'PRESS PAYS TO RETURN',
    'screen.mini': 'MINI',
    'screen.minor': 'MINOR',
    'screen.major': 'MAJOR',
    'screen.service': 'SERVICE REQUESTED',
    'screen.denom': '{d} DENOM',
    'screen.forgotten': 'CREDITS ON MACHINE',
    'screen.playMe': 'PLAY ME!',
    'screen.tease': 'GOOD LUCK…',

    'meter.credits': 'CREDITS',
    'meter.bet': 'BET',
    'meter.paid': 'WINNER PAID',

    'ui.cash': 'Cash',
    'ui.insertBill': 'Insert a bill',
    'ui.tickets': 'Your tickets',
    'ui.noTickets': 'No tickets in your pockets',
    'ui.ticketBad': 'The machine spits the ticket back out.',
    'ui.ticketOther': 'This ticket is from another casino.',
    'ui.notEnough': 'Not enough cash.',
    'ui.credits': 'Credits',
    'ui.spin': 'Spin',
    'ui.pull': 'Pull',
    'ui.betOne': 'Bet one',
    'ui.betMax': 'Bet max',
    'ui.betMinus': 'Bet –',
    'ui.betPlus': 'Bet +',
    'ui.lines': 'Lines',
    'ui.maxBet': 'Max bet',
    'ui.cashOut': 'Cash out',
    'ui.pays': 'Pays',
    'ui.ticketPrinted': 'Ticket {amt} — in your pocket',
    'ui.creditsLeft': 'You left {amt} on the machine.',
    'ui.keys': 'Space spin · ↑↓ bet · L lines · M max',
    'ui.locked': 'Machine locked — waiting for the attendant.',
    'ui.attendantComing': 'An attendant is on the way…',

    'w2g.title': 'Form W-2G',
    'w2g.subtitle': 'Certain Gambling Winnings',
    'w2g.payer': 'Payer',
    'w2g.payerName': 'Eldorado Resort Casino · Reno, NV',
    'w2g.winner': 'Winner',
    'w2g.box1': '1 Reportable winnings',
    'w2g.box2': '2 Date won',
    'w2g.box3': '3 Type of wager',
    'w2g.box4': '4 Federal income tax withheld',
    'w2g.box7': '7 Window / Machine',
    'w2g.slot': 'Slot machine',
    'w2g.explain':
      'Slot jackpots of $1,200 or more are reported to the IRS. If you give your Social Security number, nothing is withheld here — you settle it on your tax return. If you decline, the casino must withhold 24% backup withholding (federal). Nevada has no state income tax.',
    'w2g.giveSsn': 'Give SSN — paid in full',
    'w2g.decline': 'Decline — 24% withheld',
    'w2g.sign': 'Sign & take cash',
    'w2g.net': 'You receive',
    'w2g.ssnMasked': 'XXX-XX-{d}',
    'w2g.noSsn': 'Not provided',
    'w2g.attendant': 'Slot attendant',
  },
  es: {
    'btn.cashout': 'COBRAR',
    'btn.help': 'PAGOS',
    'btn.lines': 'LÍNEAS',
    'btn.betminus': 'APUESTA –',
    'btn.betplus': 'APUESTA +',
    'btn.maxbet': 'APUESTA\nMÁX',
    'btn.service': 'SERVICIO',
    'btn.betone': 'APOSTAR\nUNO',
    'btn.betmax': 'APOSTAR\nMÁX',
    'btn.spin': 'GIRAR',
    'btn.repeat': 'GIRAR',
    'club.line1': 'CLUB SILVERLODE',
    'club.line2': 'INSERTE TARJETA',

    'screen.credit': 'CRÉDITO',
    'screen.bet': 'APUESTA',
    'screen.win': 'GANANCIA',
    'screen.paid': 'PAGADO',
    'screen.lines': '{n} LÍNEAS × {b}',
    'screen.ways': '243 FORMAS × {b}',
    'screen.insert': 'INSERTE BILLETE O TICKET',
    'screen.press': 'PULSE GIRAR PARA JUGAR',
    'screen.goodLuck': '¡BUENA SUERTE!',
    'screen.noCredit': 'INSERTE MÁS CRÉDITOS',
    'screen.linePays': 'LÍNEA {n} PAGA {amt}',
    'screen.waysPays': '{sym} × {ways} FORMAS PAGA {amt}',
    'screen.scatterPays': 'SCATTER PAGA {amt}',
    'screen.totalWin': 'GANANCIA TOTAL {amt}',
    'screen.free': 'JUEGOS GRATIS',
    'screen.freeOf': 'JUEGO GRATIS {i} DE {n}',
    'screen.freeWon': '¡{n} JUEGOS GRATIS!',
    'screen.freeMore': '+{n} JUEGOS GRATIS',
    'screen.freeTotal': 'GANANCIA JUEGOS GRATIS',
    'screen.sticky': 'COMODINES FIJOS',
    'screen.expand': 'COMODINES PLATILLO SE EXPANDEN',
    'screen.hold': 'HOLD & SPIN',
    'screen.respins': 'GIROS RESTANTES',
    'screen.holdTotal': 'PERLAS PAGAN',
    'screen.bigWin': 'GRAN PREMIO',
    'screen.hugeWin': 'PREMIO ENORME',
    'screen.megaWin': 'MEGA PREMIO',
    'screen.jackpot': 'JACKPOT',
    'screen.handpay': 'PAGO MANUAL',
    'screen.callAttendant': 'LLAME AL ASISTENTE',
    'screen.handpayAmt': 'JACKPOT {amt} — ESPERE POR FAVOR',
    'screen.ticket': 'IMPRIMIENDO TICKET {amt}',
    'screen.take': 'TOME SU TICKET',
    'screen.cashedOut': 'COBRADO {amt}',
    'screen.paytable': 'TABLA DE PAGOS',
    'screen.payHelpLines': 'Se paga de izquierda a derecha en líneas jugadas. El comodín sustituye todo menos el scatter.',
    'screen.payHelpWays': '243 formas: pagan en rodillos adyacentes desde la izquierda. Los platillos (rodillos 2–4) se expanden.',
    'screen.payHelpWest': '3+ carteles de SE BUSCA: 8 / 12 / 20 juegos gratis. Los comodines se quedan fijos.',
    'screen.payHelpSpace': '3 planetas: 10 juegos gratis. Cada rodillo expandido multiplica.',
    'screen.payHelpDragon': '6+ perlas de fuego: HOLD & SPIN. 3 lingotes: 8 juegos gratis. Llena las 15 para el MAJOR.',
    'screen.touchToClose': 'PULSE PAGOS PARA VOLVER',
    'screen.mini': 'MINI',
    'screen.minor': 'MINOR',
    'screen.major': 'MAJOR',
    'screen.service': 'SERVICIO SOLICITADO',
    'screen.denom': 'DENOMINACIÓN {d}',
    'screen.forgotten': 'CRÉDITOS EN LA MÁQUINA',
    'screen.playMe': '¡JUÉGAME!',
    'screen.tease': 'SUERTE…',

    'meter.credits': 'CRÉDITOS',
    'meter.bet': 'APUESTA',
    'meter.paid': 'PAGADO',

    'ui.cash': 'Efectivo',
    'ui.insertBill': 'Meter un billete',
    'ui.tickets': 'Tus tickets',
    'ui.noTickets': 'No tienes tickets en los bolsillos',
    'ui.ticketBad': 'La máquina escupe el ticket.',
    'ui.ticketOther': 'Este ticket es de otro casino.',
    'ui.notEnough': 'No te alcanza el efectivo.',
    'ui.credits': 'Créditos',
    'ui.spin': 'Girar',
    'ui.pull': 'Jalar',
    'ui.betOne': 'Apostar uno',
    'ui.betMax': 'Apostar máx',
    'ui.betMinus': 'Apuesta –',
    'ui.betPlus': 'Apuesta +',
    'ui.lines': 'Líneas',
    'ui.maxBet': 'Apuesta máx',
    'ui.cashOut': 'Cobrar',
    'ui.pays': 'Pagos',
    'ui.ticketPrinted': 'Ticket {amt} — en tu bolsillo',
    'ui.creditsLeft': 'Dejaste {amt} en la máquina.',
    'ui.keys': 'Espacio girar · ↑↓ apuesta · L líneas · M máx',
    'ui.locked': 'Máquina bloqueada — esperando al asistente.',
    'ui.attendantComing': 'Un asistente viene en camino…',

    'w2g.title': 'Formulario W-2G',
    'w2g.subtitle': 'Ciertas ganancias de juego',
    'w2g.payer': 'Pagador',
    'w2g.payerName': 'Eldorado Resort Casino · Reno, NV',
    'w2g.winner': 'Ganador',
    'w2g.box1': '1 Ganancias declarables',
    'w2g.box2': '2 Fecha',
    'w2g.box3': '3 Tipo de apuesta',
    'w2g.box4': '4 Impuesto federal retenido',
    'w2g.box7': '7 Ventanilla / Máquina',
    'w2g.slot': 'Máquina tragamonedas',
    'w2g.explain':
      'Los jackpots de tragamonedas de $1,200 o más se reportan al IRS. Si das tu número de Seguro Social, no se retiene nada aquí: lo arreglas en tu declaración. Si te niegas, el casino debe retener 24% (retención federal de respaldo). Nevada no tiene impuesto estatal sobre la renta.',
    'w2g.giveSsn': 'Dar SSN — pago completo',
    'w2g.decline': 'Negarse — se retiene 24%',
    'w2g.sign': 'Firmar y tomar el efectivo',
    'w2g.net': 'Recibes',
    'w2g.ssnMasked': 'XXX-XX-{d}',
    'w2g.noSsn': 'No proporcionado',
    'w2g.attendant': 'Asistente de tragamonedas',
  },
});
