// Player-facing text for the Starlite Motel (signs, notices, printed labels), English + Spanish.
// Proper names on signage ("STARLITE MOTEL") stay in English in both languages, like the real
// sign would; the small print around them is translated.
import { i18n } from '../../core/i18n.js';

i18n.register('motel', {
  en: {
    name: 'STARLITE MOTEL',
    vacancy: 'VACANCY',
    no: 'NO',
    tagline: 'COLOR TV · AIR COND · WEEKLY RATES',
    office: 'OFFICE',
    ice: 'ICE',
    outOfOrder: 'OUT OF ORDER',
    noRefunds: 'NO REFUNDS',
    noRefundsSmall: 'CHECK OUT 11 AM · NO VISITORS AFTER 10 PM · CASH ONLY',
    ring: 'RING BELL',
    dnd: 'DO NOT DISTURB',
    dndSmall: 'PLEASE',
    fireMap: 'IN CASE OF FIRE',
    fireMapSmall: 'YOU ARE HERE · USE STAIRS · DO NOT USE ELEVATOR',
    noElevator: '(there is no elevator)',
    brochures: 'SEE RENO!',
    pool: 'POOL CLOSED',
    poolSmall: 'NO LIFEGUARD ON DUTY · SWIM AT OWN RISK',
    laundry: 'LAUNDRY',
    soda: 'ICE COLD',
    mints: 'MINTS',
    'it.thing': 'Thing',
    'it.switch': 'Light switch',
    'it.door': 'Door',
    'it.bathDoor': 'Bathroom door',
    'it.officeDoor': 'Office door',
    'it.curtains': 'Curtains',
    'it.sheers': 'Sheers',
    'it.fridge': 'Mini-fridge',
    'it.drawer': 'Drawer',
    'it.lamp': 'Lamp',
    'it.tv': 'TV',
    'it.ac': 'Air conditioner',
    'it.shower': 'Shower',
    'it.sink': 'Faucet',
    'it.toilet': 'Flush',
    'it.closet': 'Closet light',
    'it.fan': 'Exhaust fan',
    'it.bell': 'Bell',
    'it.microwave': 'Microwave',
    clock: '12:00',
  },
  es: {
    name: 'STARLITE MOTEL',
    vacancy: 'VACANCY',
    no: 'NO',
    tagline: 'TV A COLOR · AIRE ACOND · TARIFAS SEMANALES',
    office: 'OFICINA',
    ice: 'HIELO',
    outOfOrder: 'FUERA DE SERVICIO',
    noRefunds: 'NO HAY REEMBOLSOS',
    noRefundsSmall: 'SALIDA 11 AM · SIN VISITAS DESPUÉS DE LAS 10 PM · SOLO EFECTIVO',
    ring: 'TOQUE EL TIMBRE',
    dnd: 'NO MOLESTAR',
    dndSmall: 'POR FAVOR',
    fireMap: 'EN CASO DE INCENDIO',
    fireMapSmall: 'USTED ESTÁ AQUÍ · USE LAS ESCALERAS · NO USE EL ELEVADOR',
    noElevator: '(no hay elevador)',
    brochures: '¡CONOZCA RENO!',
    pool: 'PISCINA CERRADA',
    poolSmall: 'SIN SALVAVIDAS · NADE BAJO SU PROPIO RIESGO',
    laundry: 'LAVANDERÍA',
    soda: 'BIEN FRÍO',
    mints: 'MENTAS',
    'it.thing': 'Cosa',
    'it.switch': 'Interruptor',
    'it.door': 'Puerta',
    'it.bathDoor': 'Puerta del baño',
    'it.officeDoor': 'Puerta de la oficina',
    'it.curtains': 'Cortinas',
    'it.sheers': 'Visillos',
    'it.fridge': 'Minirefrigerador',
    'it.drawer': 'Cajón',
    'it.lamp': 'Lámpara',
    'it.tv': 'Tele',
    'it.ac': 'Aire acondicionado',
    'it.shower': 'Regadera',
    'it.sink': 'Llave del lavabo',
    'it.toilet': 'Jalar la cadena',
    'it.closet': 'Luz del clóset',
    'it.fan': 'Extractor',
    'it.bell': 'Timbre',
    'it.microwave': 'Microondas',
    clock: '12:00',
  },
});
