// Casino floor strings (lane A): signage, staff lines, the cashier cage, kiosks, the ATM.
// English + Spanish. Registered into the 'casino' namespace (station.js adds 'casino.station.*')
// and a few 'life.item.*' keys so the pockets view can label TITO tickets and chip stacks.
import { i18n } from '../core/i18n.js';

i18n.register('casino', {
  en: {
    // Signage
    'sign.cashier': 'CASHIER',
    'sign.cage': 'Cage · Chips · Tickets · Markers',
    'sign.restrooms': 'RESTROOMS',
    'sign.men': 'MEN',
    'sign.women': 'WOMEN',
    'sign.elevators': 'HOTEL ELEVATORS',
    'sign.hotelGuests': 'Hotel guests only · Room key required',
    'sign.players': 'PLAYERS CLUB',
    'sign.playersSub': 'Sign up · Earn comps · Free play',
    'sign.bar': 'FORTUNE BAR',
    'sign.barSub': 'Cocktails · Draft beer · Video poker',
    'sign.skyway': 'SKYWAY TO SILVER LEGACY · CIRCUS CIRCUS',
    'sign.skywayClosed': 'Skyway closed for renovation',
    'sign.tables': 'TABLE GAMES',
    'sign.slots': 'SLOTS',
    'sign.closed': 'TABLE CLOSED',
    'sign.craps': 'CRAPS',
    'sign.baccarat': 'BACCARAT',
    'sign.threeCard': 'THREE CARD POKER',
    'sign.minBet': '${min} MIN · ${max} MAX',
    'sign.atm': 'ATM',
    'sign.atmFee': 'Fee $8.00',
    'sign.kiosk': 'TICKET REDEMPTION',
    'sign.security': 'SECURITY',
    'sign.age': 'You must be 21 or older to enter the casino floor. Valid ID required.',
    'sign.exit': 'EXIT',
    'sign.virginia': 'Virginia St',
    'sign.fourth': '4th St',
    'sign.fountain': 'Fountain of Fortune',
    // Interactables
    'it.door': 'Door',
    'it.restroomDoor': 'Restroom (closed for cleaning)',
    'it.elevator': 'Hotel elevator',
    'it.escalator': 'Escalator to the skyway',
    'it.fountain': 'Toss a coin',
    'it.cage': 'Cashier window',
    'it.kiosk': 'Ticket redemption kiosk',
    'it.atm': 'ATM',
    'it.guard': 'Security',
    'it.bartender': 'Bartender',
    'it.players': 'Players club',
    'it.closedTable': 'Closed table',
    // Messages
    'msg.restroomClosed': 'A sign on the door: closed for cleaning, please use the restrooms by the bar.',
    'msg.elevatorKey': 'The elevator needs a hotel room key.',
    'msg.skyway': 'A stanchion and a sign: the skyway is closed for renovation.',
    'msg.coin': 'You toss a quarter in and make a wish.',
    'msg.coinBroke': 'You don\'t even have a quarter.',
    'msg.tableClosed': 'This table is covered. Opens on weekends.',
    'msg.playersSoon': 'The desk is unattended. A card says: back in 10 minutes.',
    // Guard
    'guard.id': 'Evening. Can I see some ID?',
    'guard.welcome': 'Welcome to the Eldorado. Good luck.',
    'guard.welcomeBack': 'Good luck in there.',
    'guard.ok': 'Thanks. Enjoy your night.',
    'guard.under': 'Sorry, you have to be twenty-one to be on the casino floor. I\'ll walk you out.',
    'guard.noId': 'No ID, no entry. Come back with your wallet.',
    'guard.hi': 'Need something? Cage is straight back on the left.',
    // Cashier
    'cage.title': 'Cashier',
    'cage.kicker': 'ELDORADO · CAGE',
    'cage.hello': 'Hi there. What can I do for you?',
    'cage.hello2': 'Next guest! How can I help?',
    'cage.hello3': 'Hey, welcome back.',
    'cage.tabBuy': 'Buy chips',
    'cage.tabCash': 'Cash out',
    'cage.tabTito': 'Tickets',
    'cage.cash': 'Cash in pocket',
    'cage.chips': 'Eldorado chips',
    'cage.all': 'All cash',
    'cage.custom': 'Other amount',
    'cage.buy': 'Buy {amount}',
    'cage.bought': 'Here you go, {amount} in chips. Good luck!',
    'cage.short': 'You don\'t have that much cash.',
    'cage.noCash': 'You don\'t have any cash on you.',
    'cage.min': 'Minimum is one dollar.',
    'cage.cashOut': 'Cash out {amount}',
    'cage.cashedOut': '{amount}. Counting it out for you.',
    'cage.noChips': 'You don\'t have any of our chips.',
    'cage.foreign': 'These are {casino} chips. You\'ll have to cash those at the {casino} cage.',
    'cage.redeem': 'Redeem',
    'cage.redeemAll': 'Redeem all {amount}',
    'cage.redeemed': '{amount} for your ticket.',
    'cage.expired': 'Sorry, this ticket expired. Vouchers are only good for ninety days.',
    'cage.otherCasino': 'This ticket is from {casino}. You\'ll need to redeem it there.',
    'cage.noTickets': 'No tickets in your pockets.',
    'cage.ticket': 'Ticket {amount}',
    'cage.issued': 'Issued {date}',
    'cage.done': 'Done',
    'cage.bye': 'Have a good one.',
    'cage.denoms': 'You get',
    'cage.count': 'Counting: {amount}',
    // Kiosk
    'kiosk.title': 'Ticket Redemption',
    'kiosk.kicker': 'TITO KIOSK',
    'kiosk.insert': 'Insert a ticket',
    'kiosk.paid': 'Take your cash: {bills} in bills and {coins} in coins.',
    'kiosk.paidBills': 'Take your cash: {bills}.',
    'kiosk.none': 'No tickets. Slot machines print a ticket when you cash out.',
    // ATM
    'atm.title': 'ATM',
    'atm.kicker': 'CASH ACCESS',
    'atm.balance': 'Available balance',
    'atm.fee': 'This terminal charges a $8.00 fee. Continue?',
    'atm.withdraw': 'Withdraw {amount}',
    'atm.insufficient': 'Insufficient funds. Transaction declined.',
    'atm.dispensed': 'Please take your cash: {amount}. Fee: $8.00.',
    'atm.noBank': 'Your account balance is $0.00.',
    'atm.cancel': 'Cancel',
    // Bartender / pit boss
    'bar.hi': 'What can I get you? Kitchen\'s closed but the taps are open.',
    'bar.soon': 'Give me a sec, hon.',
    'pit.hi': 'Tables are open. Five dollar blackjack on the left.',
    'pit.watch': 'Good luck, sir.',
    'pit.watchF': 'Good luck, ma\'am.',
    'npc.cheer': 'Yes! Come on!',
  },
  es: {
    'sign.cashier': 'CAJA',
    'sign.cage': 'Caja · Fichas · Tickets · Créditos',
    'sign.restrooms': 'BAÑOS',
    'sign.men': 'HOMBRES',
    'sign.women': 'MUJERES',
    'sign.elevators': 'ELEVADORES DEL HOTEL',
    'sign.hotelGuests': 'Solo huéspedes · Se requiere llave de habitación',
    'sign.players': 'CLUB DE JUGADORES',
    'sign.playersSub': 'Inscríbete · Gana cortesías · Juego gratis',
    'sign.bar': 'FORTUNE BAR',
    'sign.barSub': 'Cócteles · Cerveza de barril · Video póker',
    'sign.skyway': 'PASARELA A SILVER LEGACY · CIRCUS CIRCUS',
    'sign.skywayClosed': 'Pasarela cerrada por remodelación',
    'sign.tables': 'JUEGOS DE MESA',
    'sign.slots': 'TRAGAMONEDAS',
    'sign.closed': 'MESA CERRADA',
    'sign.craps': 'DADOS',
    'sign.baccarat': 'BACARÁ',
    'sign.threeCard': 'PÓKER DE TRES CARTAS',
    'sign.minBet': 'MÍN ${min} · MÁX ${max}',
    'sign.atm': 'CAJERO',
    'sign.atmFee': 'Comisión $8.00',
    'sign.kiosk': 'CANJE DE TICKETS',
    'sign.security': 'SEGURIDAD',
    'sign.age': 'Debes tener 21 años o más para entrar al casino. Se requiere identificación.',
    'sign.exit': 'SALIDA',
    'sign.virginia': 'Virginia St',
    'sign.fourth': '4th St',
    'sign.fountain': 'Fuente de la Fortuna',
    'it.door': 'Puerta',
    'it.restroomDoor': 'Baño (cerrado por limpieza)',
    'it.elevator': 'Elevador del hotel',
    'it.escalator': 'Escalera a la pasarela',
    'it.fountain': 'Lanzar una moneda',
    'it.cage': 'Ventanilla de caja',
    'it.kiosk': 'Kiosco de canje de tickets',
    'it.atm': 'Cajero automático',
    'it.guard': 'Seguridad',
    'it.bartender': 'Cantinero',
    'it.players': 'Club de jugadores',
    'it.closedTable': 'Mesa cerrada',
    'msg.restroomClosed': 'Un letrero en la puerta: cerrado por limpieza, usa los baños junto al bar.',
    'msg.elevatorKey': 'El elevador necesita una llave de habitación.',
    'msg.skyway': 'Un poste y un letrero: la pasarela está cerrada por remodelación.',
    'msg.coin': 'Lanzas una moneda de 25 centavos y pides un deseo.',
    'msg.coinBroke': 'Ni siquiera tienes una moneda.',
    'msg.tableClosed': 'Esta mesa está cubierta. Abre los fines de semana.',
    'msg.playersSoon': 'No hay nadie en el mostrador. Un letrero dice: regreso en 10 minutos.',
    'guard.id': 'Buenas noches. ¿Me permite una identificación?',
    'guard.welcome': 'Bienvenido al Eldorado. Buena suerte.',
    'guard.welcomeBack': 'Buena suerte ahí dentro.',
    'guard.ok': 'Gracias. Disfrute la noche.',
    'guard.under': 'Lo siento, hay que tener veintiún años para estar en el casino. Lo acompaño a la salida.',
    'guard.noId': 'Sin identificación no se entra. Vuelva con su cartera.',
    'guard.hi': '¿Necesita algo? La caja está al fondo a la izquierda.',
    'cage.title': 'Caja',
    'cage.kicker': 'ELDORADO · CAJA',
    'cage.hello': 'Hola. ¿En qué le puedo ayudar?',
    'cage.hello2': '¡Siguiente! ¿Qué necesita?',
    'cage.hello3': 'Hola, bienvenido de nuevo.',
    'cage.tabBuy': 'Comprar fichas',
    'cage.tabCash': 'Cambiar fichas',
    'cage.tabTito': 'Tickets',
    'cage.cash': 'Efectivo en el bolsillo',
    'cage.chips': 'Fichas del Eldorado',
    'cage.all': 'Todo el efectivo',
    'cage.custom': 'Otra cantidad',
    'cage.buy': 'Comprar {amount}',
    'cage.bought': 'Aquí tiene, {amount} en fichas. ¡Suerte!',
    'cage.short': 'No tienes tanto efectivo.',
    'cage.noCash': 'No traes efectivo.',
    'cage.min': 'El mínimo es un dólar.',
    'cage.cashOut': 'Cambiar {amount}',
    'cage.cashedOut': '{amount}. Se los cuento.',
    'cage.noChips': 'No tiene fichas nuestras.',
    'cage.foreign': 'Estas son fichas de {casino}. Tiene que cambiarlas en la caja de {casino}.',
    'cage.redeem': 'Canjear',
    'cage.redeemAll': 'Canjear todo {amount}',
    'cage.redeemed': '{amount} por su ticket.',
    'cage.expired': 'Lo siento, este ticket venció. Solo valen noventa días.',
    'cage.otherCasino': 'Este ticket es de {casino}. Tiene que canjearlo allá.',
    'cage.noTickets': 'No tienes tickets en los bolsillos.',
    'cage.ticket': 'Ticket {amount}',
    'cage.issued': 'Emitido {date}',
    'cage.done': 'Listo',
    'cage.bye': 'Que le vaya bien.',
    'cage.denoms': 'Recibes',
    'cage.count': 'Contando: {amount}',
    'kiosk.title': 'Canje de Tickets',
    'kiosk.kicker': 'KIOSCO TITO',
    'kiosk.insert': 'Inserte un ticket',
    'kiosk.paid': 'Tome su dinero: {bills} en billetes y {coins} en monedas.',
    'kiosk.paidBills': 'Tome su dinero: {bills}.',
    'kiosk.none': 'No hay tickets. Las tragamonedas imprimen uno al cobrar.',
    'atm.title': 'Cajero',
    'atm.kicker': 'ACCESO A EFECTIVO',
    'atm.balance': 'Saldo disponible',
    'atm.fee': 'Este cajero cobra una comisión de $8.00. ¿Continuar?',
    'atm.withdraw': 'Retirar {amount}',
    'atm.insufficient': 'Fondos insuficientes. Transacción rechazada.',
    'atm.dispensed': 'Tome su efectivo: {amount}. Comisión: $8.00.',
    'atm.noBank': 'El saldo de tu cuenta es $0.00.',
    'atm.cancel': 'Cancelar',
    'bar.hi': '¿Qué te sirvo? La cocina cerró pero las llaves están abiertas.',
    'bar.soon': 'Dame un segundo, cariño.',
    'pit.hi': 'Las mesas están abiertas. Blackjack de cinco dólares a la izquierda.',
    'pit.watch': 'Buena suerte, señor.',
    'pit.watchF': 'Buena suerte, señora.',
    'npc.cheer': '¡Sí! ¡Vamos!',
  },
});

// Pocket item labels (the pockets view reads life.item.<kind> / life.item.<kind>.desc).
i18n.register('life', {
  en: {
    'item.tito': 'Slot ticket',
    'item.tito.desc': 'A cash-out voucher from a slot machine. Cash it at a kiosk or the cage, or play it in another machine. Good for 90 days.',
    'item.chips': 'Casino chips',
    'item.chips.desc': '{number} in {name} chips. Only the {name} cage will cash them.',
  },
  es: {
    'item.tito': 'Ticket de tragamonedas',
    'item.tito.desc': 'Un vale de cobro de una tragamonedas. Cámbialo en un kiosco o en la caja, o juégalo en otra máquina. Vale 90 días.',
    'item.chips': 'Fichas de casino',
    'item.chips.desc': '{number} en fichas de {name}. Solo la caja de {name} las cambia.',
  },
});
