/* AI Play - two tiny practice games that get added to the library the first time you open AI Play.
 * They're simple on purpose, so you can actually WATCH the AI get better at them.
 */
'use strict';

AIP.practice = [
  {
    name: 'Coin Dodge',
    html: [
      '<!DOCTYPE html><html><head><meta charset="utf-8"><title>Coin Dodge</title>',
      '<style>html,body{margin:0;height:100%;background:#0b1030;overflow:hidden;font-family:Segoe UI,Arial,sans-serif;color:#fff}',
      'canvas{display:block;width:100%;height:100%}',
      '#menu{position:fixed;inset:0;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:14px;background:rgba(8,10,35,.82);text-align:center}',
      '#menu h1{margin:0;font-size:52px;color:#ffd84a;text-shadow:0 4px 0 #a86d05}',
      '#menu p{margin:0;color:#b9c3ff;font-size:18px}',
      'button{font-size:24px;font-weight:800;padding:12px 34px;border:0;border-radius:12px;background:#ffd84a;color:#3a2600;cursor:pointer;box-shadow:0 5px 0 #a86d05}',
      '.hidden{display:none!important}</style></head><body>',
      '<canvas id="c"></canvas>',
      '<div id="menu"><h1 id="mt">COIN DODGE</h1><p id="ms">Move with ← → (or A / D). Catch the yellow coins. Dodge the red blocks!</p><button id="go">PLAY</button></div>',
      '<script>',
      'var c=document.getElementById("c"),x=c.getContext("2d"),W=0,H=0;',
      'function size(){W=c.width=innerWidth;H=c.height=innerHeight;}size();addEventListener("resize",size);',
      'var keys={},st="menu",p,things,score,lives,best=+(localStorage.getItem("coinDodgeBest")||0),t0,spawn,flash=0,last=performance.now();',
      'addEventListener("keydown",function(e){keys[e.code]=true;if(st==="over"&&(e.code==="Space"||e.code==="Enter"))start();if(st==="menu"&&e.code==="Enter")start();});',
      'addEventListener("keyup",function(e){keys[e.code]=false;});',
      'document.getElementById("go").onclick=function(){start();};',
      'function start(){st="play";document.getElementById("menu").classList.add("hidden");p={x:W/2,w:Math.max(60,W*.08),h:18};things=[];score=0;lives=3;t0=performance.now();spawn=0;}',
      'function over(){st="over";if(score>best){best=score;localStorage.setItem("coinDodgeBest",best);}',
      ' document.getElementById("mt").textContent="GAME OVER";document.getElementById("ms").textContent="Score: "+score+"  -  press Space to try again";',
      ' document.getElementById("go").textContent="PLAY AGAIN";document.getElementById("menu").classList.remove("hidden");}',
      'function loop(now){requestAnimationFrame(loop);var dt=Math.min(.05,(now-last)/1000);last=now;',
      ' x.fillStyle="#0b1030";x.fillRect(0,0,W,H);',
      ' x.fillStyle="#1b2458";for(var i=0;i<W;i+=60)x.fillRect(i,0,1,H);',
      ' if(st==="play"){var sp=W*.55,dir=(keys.ArrowRight||keys.KeyD?1:0)-(keys.ArrowLeft||keys.KeyA?1:0);p.x=Math.max(p.w/2,Math.min(W-p.w/2,p.x+dir*sp*dt));',
      '  var el=(now-t0)/1000;spawn-=dt;if(spawn<=0){spawn=Math.max(.22,.75-el*.01);var bad=Math.random()<Math.min(.62,.4+el*.004);',
      '   things.push({x:30+Math.random()*(W-60),y:-30,r:bad?22:15,bad:bad,v:H*(.28+Math.random()*.18+el*.003)});}',
      '  for(var j=things.length-1;j>=0;j--){var o=things[j];o.y+=o.v*dt;',
      '   if(o.y>H-60-o.r&&o.y<H-40+o.r&&Math.abs(o.x-p.x)<p.w/2+o.r*.8){things.splice(j,1);if(o.bad){lives--;flash=.25;if(lives<=0){over();}}else score+=10;continue;}',
      '   if(o.y>H+40)things.splice(j,1);}}',
      ' if(things)for(var k=0;k<things.length;k++){var q=things[k];if(q.bad){x.fillStyle="#ff3344";x.fillRect(q.x-q.r,q.y-q.r,q.r*2,q.r*2);}else{x.fillStyle="#ffd84a";x.beginPath();x.arc(q.x,q.y,q.r,0,7);x.fill();}}',
      ' if(p){x.fillStyle="#e8f4ff";x.fillRect(p.x-p.w/2,H-60,p.w,p.h);}',
      ' if(flash>0){flash-=dt;x.fillStyle="rgba(255,30,50,"+(flash*1.6)+")";x.fillRect(0,0,W,H);}',
      ' x.font="bold 26px Segoe UI,Arial";x.fillStyle="#fff";x.textAlign="left";x.fillText("Score: "+(score||0),20,40);',
      ' x.textAlign="right";x.fillText("Lives: "+(lives==null?3:lives),W-20,40);x.textAlign="center";x.fillStyle="#9aa6e6";x.font="18px Segoe UI,Arial";x.fillText("Best: "+best,W/2,36);}',
      'requestAnimationFrame(loop);',
      '</' + 'script></body></html>',
    ].join('\n'),
  },
  {
    name: 'Jump Jam',
    html: [
      '<!DOCTYPE html><html><head><meta charset="utf-8"><title>Jump Jam</title>',
      '<style>html,body{margin:0;height:100%;background:#1a0f2e;overflow:hidden;font-family:Segoe UI,Arial,sans-serif;color:#fff}',
      'canvas{display:block;width:100%;height:100%}',
      '#hud{position:fixed;left:16px;top:12px;font-size:24px;font-weight:800;text-shadow:0 2px 0 #000}',
      '#over{position:fixed;inset:0;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:12px;background:rgba(20,5,30,.75);text-align:center}',
      '#over h1{margin:0;font-size:48px;color:#ff8a3d}#over p{margin:0;color:#e6d4ff;font-size:18px}',
      'button{font-size:22px;font-weight:800;padding:10px 30px;border:0;border-radius:12px;background:#7dff9a;color:#08300f;cursor:pointer}',
      '.hidden{display:none!important}</style></head><body>',
      '<canvas id="c"></canvas>',
      '<div id="hud">Score: <b id="score">0</b></div>',
      '<div id="over"><h1 id="ot">JUMP JAM</h1><p id="os">Press Space (or ↑) to jump over the red spikes. Grab the yellow stars!</p><button id="go">Start</button></div>',
      '<script>',
      'var c=document.getElementById("c"),x=c.getContext("2d"),W,H,G;function size(){W=c.width=innerWidth;H=c.height=innerHeight;G=H*.78;}size();addEventListener("resize",size);',
      'var st="menu",pl,obs,stars,score,dist,spd,cool,last=performance.now(),sEl=document.getElementById("score");',
      'function jump(){if(st!=="play")return;if(pl.y>=G-pl.s-1){pl.vy=-H*1.25;}}',
      'addEventListener("keydown",function(e){if(e.code==="Space"||e.code==="ArrowUp"||e.code==="KeyW"){if(st!=="play"){start();return;}jump();}});',
      'document.getElementById("go").onclick=function(){start();};',
      'function start(){st="play";document.getElementById("over").classList.add("hidden");pl={x:W*.18,y:G-40,s:40,vy:0};obs=[];stars=[];score=0;dist=0;spd=W*.42;cool=1;}',
      'function crash(){st="over";document.getElementById("ot").textContent="YOU CRASHED";document.getElementById("os").textContent="Score "+score+". Press Space to try again!";',
      ' document.getElementById("go").textContent="Try again";document.getElementById("over").classList.remove("hidden");}',
      'function loop(now){requestAnimationFrame(loop);var dt=Math.min(.05,(now-last)/1000);last=now;',
      ' x.fillStyle="#1a0f2e";x.fillRect(0,0,W,H);x.fillStyle="#3b2a63";x.fillRect(0,G,W,H-G);',
      ' if(st==="play"){spd+=dt*6;dist+=spd*dt;pl.vy+=H*3.6*dt;pl.y+=pl.vy*dt;if(pl.y>G-pl.s){pl.y=G-pl.s;pl.vy=0;}',
      '  cool-=dt;if(cool<=0){cool=.9+Math.random()*1.1;obs.push({x:W+20,w:26+Math.random()*24,h:30+Math.random()*30});if(Math.random()<.6)stars.push({x:W+120,y:G-90-Math.random()*H*.18});}',
      '  for(var i=obs.length-1;i>=0;i--){var o=obs[i];o.x-=spd*dt;if(o.x<-60){obs.splice(i,1);continue;}',
      '   if(pl.x+pl.s>o.x+4&&pl.x<o.x+o.w-4&&pl.y+pl.s>G-o.h+4){crash();}}',
      '  for(var j=stars.length-1;j>=0;j--){var s=stars[j];s.x-=spd*dt;if(s.x<-40){stars.splice(j,1);continue;}',
      '   if(Math.abs(s.x-(pl.x+pl.s/2))<34&&Math.abs(s.y-(pl.y+pl.s/2))<40){stars.splice(j,1);score+=25;}}',
      '  var d=Math.floor(dist/W*10);if(d>(pl.d||0)){score+=d-(pl.d||0);pl.d=d;}sEl.textContent=score;}',
      ' if(obs)for(var k=0;k<obs.length;k++){var q=obs[k];x.fillStyle="#ff3344";x.beginPath();x.moveTo(q.x,G);x.lineTo(q.x+q.w/2,G-q.h);x.lineTo(q.x+q.w,G);x.fill();}',
      ' if(stars)for(var m=0;m<stars.length;m++){x.fillStyle="#ffd84a";x.beginPath();x.arc(stars[m].x,stars[m].y,13,0,7);x.fill();}',
      ' if(pl){x.fillStyle="#5ad7ff";x.fillRect(pl.x,pl.y,pl.s,pl.s);x.fillStyle="#0b1a30";x.fillRect(pl.x+24,pl.y+10,7,7);}}',
      'requestAnimationFrame(loop);',
      '</' + 'script></body></html>',
    ].join('\n'),
  },
];
