// Table games text (EN + ES): controls, dealer / pit boss / player lines. Namespace 'tables'.
// Lines with several variants are '|' separated; pick one with line(key, vars).
import { i18n, t } from '../../core/i18n.js';

i18n.register('tables', {
  en: {
    // controls
    deal: 'Deal',
    hit: 'Hit',
    stand: 'Stand',
    double: 'Double',
    split: 'Split',
    insurance: 'Insurance',
    evenMoney: 'Even money',
    noInsurance: 'No thanks',
    clear: 'Clear',
    rebet: 'Rebet',
    allIn: 'All in',
    change: 'Change',
    changeTitle: 'Buy chips with cash',
    cancel: 'Cancel',
    spin: 'Spin',
    buyIn: 'Buy in',
    buyInTitle: 'Wheel chips',
    chipValue: 'Each chip worth',
    pay: 'Pay with',
    payChips: 'Casino chips',
    payCash: 'Cash',
    all: 'All',
    bet: 'Bet',
    yourChips: 'Chips',
    cashLeft: 'Cash',
    minMax: '{min} – {max}',
    h17: 'Dealer hits soft 17',
    s17: 'Dealer stands on all 17s',
    bjPays: 'Blackjack pays 3 to 2',
    insPays: 'Insurance pays 2 to 1',
    rouletteMin: 'Inside {inside} per spot · Outside {min}',
    hintBet: 'Tap your chips to bet · drag them onto the circle',
    hintRoulette: 'Pick a stack, then tap the layout · drag chips onto lines and corners',
    hintTurn: 'H hit · S stand · D double · Q split',
    waitTurn: 'Waiting for the other players…',
    noChips: 'No chips here — change some cash',
    noCash: 'You have no cash',
    under: 'Minimum bet is {min}',
    over: 'Table maximum is {max}',
    outsideMin: 'Outside bets are {min} minimum',
    insideMin: 'Inside bets need {min} in total',
    straightMax: 'Straight-up maximum is {max}',
    betsOff: 'Bets are closed',
    standBusy: 'Finish the hand first.',
    standWheel: 'Wait for the ball.',
    youWin: 'You win {amount}',
    youLose: 'You lose {amount}',
    push: 'Push',
    totalSoft: '{lo}/{hi}',
    // dealer
    'd.greet': 'Welcome in! Good luck.|Hey there, how we doing?|Evening! Grab a seat.|Welcome, buy in whenever you\'re ready.',
    'd.bets': 'Place your bets.|Bets, please.|Get your bets in.',
    'd.noMore': 'No more bets!|No more bets, thank you.',
    'd.dealerHas': 'Dealer has {n}.',
    'd.dealerBust': 'Dealer busts!|Too many for me — everybody wins!',
    'd.bj': 'Blackjack! Nice.|Blackjack, there it is.|Natural! Congrats.',
    'd.dealerBJ': 'Dealer has blackjack.|Sorry folks, blackjack.',
    'd.bust': 'Too many.|That\'s a bust, sorry.',
    'd.insurance': 'Insurance? Insurance open.|Ace up — insurance anyone?',
    'd.evenMoney': 'Even money?',
    'd.noBJ': 'Nobody home. Let\'s play.|No blackjack, let\'s go.',
    'd.changing': 'Changing {amount}!',
    'd.checks': 'Checks play!|Black action!',
    'd.shuffle': 'Shuffle up — give me a minute.|New shoe coming up.',
    'd.colorUp': 'Coloring up {amount}!',
    'd.thanks': 'Thank you!|Appreciate it!|Thanks, good luck to you.',
    'd.what': 'What would you like to do?|Your call.',
    'd.double': 'Double down, one card.',
    'd.split': 'Splitting.',
    'd.winner': '{n} {color}.|{n}, {color}.',
    'd.green': '{n}, green!|Green {n}!',
    'd.spin': 'Here we go.|Good luck, everybody.',
    'd.relief': 'Hi folks, I\'ll be your dealer.|Fresh dealer, fresh luck.',
    'd.bye': 'Good luck, folks.|Take care, everyone.',
    'd.wheelChips': '{n} chips at {value} each. Good luck!',
    red: 'red',
    black: 'black',
    // pit boss
    'p.ok': 'Go ahead.|Okay.|Go ahead, thank you.',
    // npc
    'n.win': 'Yes!|Let\'s go!|Pay me!|Finally!',
    'n.lose': 'Ugh.|Come on…|Every time.|Unbelievable.',
    'n.bj': 'Blackjack, baby!|Woo!',
    'n.hit': 'Hit me.',
    'n.broke': 'I\'m done.|That\'s it for me.|Well, there goes rent.',
    'n.tip': 'This one\'s for you.|For the dealer.',
  },
  es: {
    deal: 'Repartir',
    hit: 'Pedir',
    stand: 'Plantarse',
    double: 'Doblar',
    split: 'Separar',
    insurance: 'Seguro',
    evenMoney: 'Pago parejo',
    noInsurance: 'No, gracias',
    clear: 'Quitar',
    rebet: 'Repetir',
    allIn: 'Todo',
    change: 'Cambio',
    changeTitle: 'Comprar fichas con efectivo',
    cancel: 'Cancelar',
    spin: 'Girar',
    buyIn: 'Comprar',
    buyInTitle: 'Fichas de ruleta',
    chipValue: 'Valor de cada ficha',
    pay: 'Pagar con',
    payChips: 'Fichas del casino',
    payCash: 'Efectivo',
    all: 'Todo',
    bet: 'Apuesta',
    yourChips: 'Fichas',
    cashLeft: 'Efectivo',
    minMax: '{min} – {max}',
    h17: 'El crupier pide con 17 suave',
    s17: 'El crupier se planta con todo 17',
    bjPays: 'Blackjack paga 3 a 2',
    insPays: 'El seguro paga 2 a 1',
    rouletteMin: 'Dentro {inside} por casilla · Fuera {min}',
    hintBet: 'Toca tus fichas para apostar · arrástralas al círculo',
    hintRoulette: 'Elige una pila y toca el tapete · arrastra fichas a líneas y esquinas',
    hintTurn: 'H pedir · S plantarse · D doblar · Q separar',
    waitTurn: 'Esperando a los demás jugadores…',
    noChips: 'No tienes fichas aquí — cambia efectivo',
    noCash: 'No tienes efectivo',
    under: 'La apuesta mínima es {min}',
    over: 'El máximo de la mesa es {max}',
    outsideMin: 'Las apuestas de fuera son de {min} mínimo',
    insideMin: 'Las apuestas de dentro suman {min} mínimo',
    straightMax: 'El máximo a pleno es {max}',
    betsOff: 'No va más',
    standBusy: 'Termina la mano primero.',
    standWheel: 'Espera a la bola.',
    youWin: 'Ganas {amount}',
    youLose: 'Pierdes {amount}',
    push: 'Empate',
    totalSoft: '{lo}/{hi}',
    'd.greet': '¡Bienvenido! Buena suerte.|¿Qué tal? Siéntese.|¡Buenas noches! Tome asiento.|Bienvenido, compre cuando quiera.',
    'd.bets': 'Hagan sus apuestas.|Apuestas, por favor.',
    'd.noMore': '¡No va más!|No va más, gracias.',
    'd.dealerHas': 'La banca tiene {n}.',
    'd.dealerBust': '¡La banca se pasa!|¡Me pasé, ganan todos!',
    'd.bj': '¡Blackjack! Bien.|Blackjack, ahí está.',
    'd.dealerBJ': 'La banca tiene blackjack.|Lo siento, blackjack.',
    'd.bust': 'Se pasó.|Se pasó, lo siento.',
    'd.insurance': '¿Seguro? Seguro abierto.|As arriba, ¿alguien quiere seguro?',
    'd.evenMoney': '¿Pago parejo?',
    'd.noBJ': 'No hay blackjack. A jugar.|Nada, sigamos.',
    'd.changing': '¡Cambio de {amount}!',
    'd.checks': '¡Juegan fichas negras!|¡Apuesta fuerte!',
    'd.shuffle': 'Barajando, un momento.|Zapato nuevo.',
    'd.colorUp': '¡Cambio a fichas grandes, {amount}!',
    'd.thanks': '¡Gracias!|¡Se agradece!|Gracias, buena suerte.',
    'd.what': '¿Qué desea hacer?|Usted decide.',
    'd.double': 'Dobla, una carta.',
    'd.split': 'Separamos.',
    'd.winner': '{n} {color}.|{n}, {color}.',
    'd.green': '¡{n}, verde!|¡Verde, {n}!',
    'd.spin': 'Allá vamos.|Suerte a todos.',
    'd.relief': 'Hola a todos, soy su crupier.|Crupier nuevo, suerte nueva.',
    'd.bye': 'Suerte, amigos.|Cuídense.',
    'd.wheelChips': '{n} fichas a {value} cada una. ¡Suerte!',
    red: 'rojo',
    black: 'negro',
    'p.ok': 'Adelante.|Está bien.|Adelante, gracias.',
    'n.win': '¡Sí!|¡Vamos!|¡Págame!|¡Por fin!',
    'n.lose': 'Uf.|Vamos…|Siempre igual.|Increíble.',
    'n.bj': '¡Blackjack!|¡Uuu!',
    'n.hit': 'Dame.',
    'n.broke': 'Ya terminé.|Hasta aquí.|Adiós a la renta.',
    'n.tip': 'Esta es para ti.|Para el crupier.',
  },
});

/** A random variant of a '|' separated line. */
export function line(key, vars, rnd = Math.random) {
  const all = t(`tables.${key}`, vars).split('|');
  return all[Math.floor(rnd() * all.length)];
}

export const tt = (key, vars) => t(`tables.${key}`, vars);

/** $5, $2.50, $1,250 */
export function money(v) {
  const cents = Math.round(v * 100) % 100 !== 0;
  return `$${v.toLocaleString('en-US', { minimumFractionDigits: cents ? 2 : 0, maximumFractionDigits: 2 })}`;
}
