// Player-facing text for the front end (boot, menu, settings, credits, loading) in English and
// Spanish. Registered once under the 'ui' namespace; read with t('ui.<key>').

import { i18n } from '../core/i18n.js';

i18n.register('ui', {
  en: {
    // Boot — content warning
    'warn.kicker': 'Before you sit down',
    'warn.title': 'Content Warning',
    'warn.body': 'Contains violence, blood, alcohol, smoking, strong language and gambling with VIRTUAL money only.',
    'warn.body2': 'No real money can be won or lost.',
    'warn.discretion': 'Player discretion is advised.',
    'warn.continue': 'Press any key to continue',
    'warn.continueTouch': 'Tap anywhere to continue',
    'warn.violence': 'Violence',
    'warn.blood': 'Blood',
    'warn.alcohol': 'Alcohol',
    'warn.smoking': 'Smoking',
    'warn.language': 'Language',
    'warn.gambling': 'Virtual gambling',
    'splash.studio': 'Loaded Dice',
    'splash.studios': 'Studios',
    'splash.presents': 'presents',
    skip: 'Skip',
    'skip.hint': 'Any key to skip',

    // Main menu
    'menu.play': 'Play',
    'menu.continue': 'Continue',
    'menu.multiplayer': 'Multiplayer',
    'menu.settings': 'Settings',
    'menu.credits': 'Credits',
    'menu.quit': 'Quit',
    'menu.hint': '↑ ↓ choose · Enter select · drag the lever',
    'menu.hintTouch': 'Tap a button · drag the lever',
    'menu.notReadyTitle': 'The doors aren’t open yet',
    'menu.notReadyBody': 'This part of Reno is still being built. Pull the lever while you wait — it’s on the house.',
    'menu.mpTitle': 'Multiplayer',
    'menu.mpBody': 'Online play arrives in a later update. We’re still polishing the chairs at your friends’ table.',
    'menu.mpFoot': 'Phones and PCs will share the same rooms.',
    'menu.ok': 'Got it',
    'menu.quitTitle': 'Cash out already?',
    'menu.quitBody': 'The machine is warm, the lights are on, and you were *this* close.',
    'menu.quitYes': 'Cash out',
    'menu.quitNo': 'One more spin',
    'menu.thanksTitle': 'Thanks for playing',
    'menu.thanksBody': 'You can close this tab now. Your life in Reno keeps ticking while you’re gone.',
    'menu.thanksBack': 'Back to the machine',
    'menu.jackpot': 'Jackpot!',
    'menu.freeplay': 'Free play · no credit',
    'menu.credit': 'Credit',

    // Settings
    'set.title': 'Settings',
    'set.subtitle': 'House rules',
    'set.done': 'Done',
    'set.reset': 'Reset table',
    'set.resetConfirm': 'Reset every setting to the house default?',
    'set.resetDone': 'Everything is back to the house defaults.',
    'tab.graphics': 'Graphics',
    'tab.audio': 'Audio',
    'tab.controls': 'Controls',
    'tab.content': 'Gameplay & Content',
    'tab.voice': 'Voice & Online',
    'tab.language': 'Language',
    'tab.access': 'Accessibility',

    quality: 'Quality',
    'quality.desc': 'Auto picks the best look your device can hold at a smooth frame rate.',
    'quality.auto': 'Auto',
    'quality.low': 'Low',
    'quality.medium': 'Medium',
    'quality.high': 'High',
    'quality.ultra': 'Ultra',
    'quality.detected': 'Auto detected: {tier}',
    resolutionScale: 'Resolution scale',
    'resolutionScale.desc': 'Lower it to gain speed on a hot phone; raise it for crisper edges.',
    fov: 'Field of view',
    'fov.desc': 'How wide the camera sees. Wider feels faster; narrower feels cinematic.',
    bloom: 'Bloom',
    'bloom.desc': 'Neon and bulbs glow into the air around them.',
    filmGrain: 'Film grain',
    'filmGrain.desc': 'A whisper of grain and vignette, like an old casino security tape.',
    motionBlur: 'Motion blur',
    'motionBlur.desc': 'Smears fast motion. Turn off if it makes you queasy.',
    lensEffects: 'Lens effects',
    'lensEffects.desc': 'Raindrops on the lens and flares from headlights.',

    masterVolume: 'Master',
    'masterVolume.desc': 'Everything at once.',
    musicVolume: 'Music',
    'musicVolume.desc': 'Lounge jazz, casino speakers and the car radio.',
    sfxVolume: 'Effects',
    'sfxVolume.desc': 'Chips, cards, doors, footsteps, punches.',
    ambienceVolume: 'Ambience',
    'ambienceVolume.desc': 'The city, the casino floor, the neighbor’s TV.',
    voiceVolume: 'Voices',
    'voiceVolume.desc': 'People talking — strangers, dealers, your friends.',
    uiVolume: 'Interface',
    'uiVolume.desc': 'Menu clicks and chip taps like these.',

    mouseSensitivity: 'Mouse sensitivity',
    'mouseSensitivity.desc': 'How far the camera turns per inch of mouse.',
    invertY: 'Invert look',
    'invertY.desc': 'Push up to look down, like a flight stick.',
    touchStyle: 'Touch controls',
    'touchStyle.desc': 'Twin joysticks, or tap where you want to walk.',
    'touchStyle.joysticks': 'Joysticks',
    'touchStyle.tap': 'Tap to move',
    'keys.title': 'Keyboard',
    'keys.move': 'Walk',
    'keys.sprint': 'Run',
    'keys.jump': 'Jump',
    'keys.crouch': 'Crouch',
    'keys.interact': 'Interact',
    'keys.use': 'Use',
    'keys.phone': 'Phone',
    'keys.pockets': 'Pockets',
    'keys.emote': 'Emotes',
    'keys.flop': 'Flop',
    'keys.talk': 'Talk',
    'keys.camera': 'Swap shoulder',
    'keys.menu': 'Menu',

    swearFilter: 'Swear filter',
    'swearFilter.desc': 'Bleeps strong language from people, radio and TV.',
    blood: 'Blood',
    'blood.desc': 'Realistic blood from fights and accidents.',
    subtitles: 'Subtitles',
    'subtitles.desc': 'Show what people say as text.',
    npcVoices: 'Stranger voices',
    'npcVoices.desc': 'How the people of Reno speak to you.',
    'npcVoices.tts': 'Real voices',
    'npcVoices.gibberish': 'Sim-speak',
    'npcVoices.text': 'Text only',

    micEnabled: 'Microphone',
    'micEnabled.desc': 'Talk with your real voice. Asks for permission the first time.',
    micMode: 'Mic mode',
    'micMode.desc': 'Always listening, or only while you hold the talk key.',
    'micMode.open': 'Open mic',
    'micMode.push': 'Push to talk',
    voiceTalkToNpcs: 'Talk to strangers',
    'voiceTalkToNpcs.desc': 'People in Reno hear and answer what you say.',
    realVoiceOut: 'Your real voice',
    'realVoiceOut.desc': 'Others hear your actual voice from your character.',
    nameTags: 'Name tags',
    'nameTags.desc': 'Floating names over friends in online rooms.',
    'voice.online': 'Online rooms arrive in a later update; these choices are saved for then.',

    language: 'Language',
    'language.desc': 'Menus, phone, signs you can read and subtitles.',
    'language.en': 'English',
    'language.es': 'Español',

    textScale: 'Text size',
    'textScale.desc': 'Scales menus, the phone and subtitles.',
    reduceFlashing: 'Reduce flashing',
    'reduceFlashing.desc': 'Calms strobing jackpots, police lights and neon flicker.',
    devOverlay: 'Performance overlay',
    'devOverlay.desc': 'Frame rate and renderer stats in the corner (F3).',

    // Loading
    'load.loading': 'Loading',
    'load.tip': 'Tip of the house',
    'load.free': 'Free spin while you wait',
    'load.spin': 'Spin',
    'load.spinAgain': 'Again',
    'load.win': 'Winner! {n} imaginary credits',
    'load.lose': 'So close.',
    'load.big': 'JACKPOT! Worth exactly nothing.',
    'load.credits': 'Credits: {n}',
    'paper.name': 'The Truckee Times',
    'paper.motto': 'Reno’s Most Honest Newspaper Since Last Tuesday',
    'paper.price': '50¢',
    'paper.edition': 'Late Edition',
    'paper.weather': 'Weather: dry heat, cold nights, wind off the Sierra',

    // Credits
    'cred.kicker': 'A Loaded Dice Studios Game',
    'cred.design': 'Game design',
    'cred.direction': 'Direction',
    'cred.code': 'Programming',
    'cred.art': 'Art & procedural modeling',
    'cred.anim': 'Animation & jiggle physics',
    'cred.audio': 'Music & sound',
    'cred.writing': 'Writing',
    'cred.qa': 'Quality assurance',
    'cred.studio': 'Loaded Dice Studios',
    'cred.original': 'All art, models, sounds and music are original and generated in code.',
    'cred.virtual': 'Virtual money only. No real money can be won or lost.',
    'cred.thirdParty': 'Built with',
    'cred.fonts': 'Typefaces',
    'cred.thanks': 'Thanks for playing.',
    'cred.back': 'Back to the machine',
  },
  es: {
    'warn.kicker': 'Antes de sentarte',
    'warn.title': 'Aviso de contenido',
    'warn.body': 'Contiene violencia, sangre, alcohol, tabaco, lenguaje fuerte y apuestas solo con dinero VIRTUAL.',
    'warn.body2': 'No se puede ganar ni perder dinero real.',
    'warn.discretion': 'Se recomienda discreción.',
    'warn.continue': 'Pulsa cualquier tecla para continuar',
    'warn.continueTouch': 'Toca en cualquier lugar para continuar',
    'warn.violence': 'Violencia',
    'warn.blood': 'Sangre',
    'warn.alcohol': 'Alcohol',
    'warn.smoking': 'Tabaco',
    'warn.language': 'Lenguaje',
    'warn.gambling': 'Apuestas virtuales',
    'splash.studio': 'Loaded Dice',
    'splash.studios': 'Studios',
    'splash.presents': 'presenta',
    skip: 'Saltar',
    'skip.hint': 'Cualquier tecla para saltar',

    'menu.play': 'Jugar',
    'menu.continue': 'Continuar',
    'menu.multiplayer': 'Multijugador',
    'menu.settings': 'Ajustes',
    'menu.credits': 'Créditos',
    'menu.quit': 'Salir',
    'menu.hint': '↑ ↓ elegir · Enter aceptar · arrastra la palanca',
    'menu.hintTouch': 'Toca un botón · arrastra la palanca',
    'menu.notReadyTitle': 'Las puertas aún no abren',
    'menu.notReadyBody': 'Esta parte de Reno todavía está en obras. Tira de la palanca mientras esperas: invita la casa.',
    'menu.mpTitle': 'Multijugador',
    'menu.mpBody': 'El juego en línea llegará en una próxima actualización. Seguimos puliendo las sillas de la mesa de tus amigos.',
    'menu.mpFoot': 'Móviles y PC compartirán las mismas salas.',
    'menu.ok': 'Entendido',
    'menu.quitTitle': '¿Ya te retiras?',
    'menu.quitBody': 'La máquina está caliente, las luces encendidas y estuviste *así* de cerca.',
    'menu.quitYes': 'Cobrar y salir',
    'menu.quitNo': 'Una tirada más',
    'menu.thanksTitle': 'Gracias por jugar',
    'menu.thanksBody': 'Ya puedes cerrar esta pestaña. Tu vida en Reno sigue su curso mientras no estás.',
    'menu.thanksBack': 'Volver a la máquina',
    'menu.jackpot': '¡Premio gordo!',
    'menu.freeplay': 'Juego libre · sin crédito',
    'menu.credit': 'Crédito',

    'set.title': 'Ajustes',
    'set.subtitle': 'Reglas de la casa',
    'set.done': 'Listo',
    'set.reset': 'Restablecer mesa',
    'set.resetConfirm': '¿Volver todos los ajustes a los de la casa?',
    'set.resetDone': 'Todo ha vuelto a los ajustes de la casa.',
    'tab.graphics': 'Gráficos',
    'tab.audio': 'Audio',
    'tab.controls': 'Controles',
    'tab.content': 'Juego y contenido',
    'tab.voice': 'Voz y en línea',
    'tab.language': 'Idioma',
    'tab.access': 'Accesibilidad',

    quality: 'Calidad',
    'quality.desc': 'Auto elige lo mejor que tu dispositivo aguanta con fluidez.',
    'quality.auto': 'Auto',
    'quality.low': 'Baja',
    'quality.medium': 'Media',
    'quality.high': 'Alta',
    'quality.ultra': 'Ultra',
    'quality.detected': 'Detectado: {tier}',
    resolutionScale: 'Escala de resolución',
    'resolutionScale.desc': 'Bájala para ganar velocidad en un móvil caliente; súbela para bordes más nítidos.',
    fov: 'Campo de visión',
    'fov.desc': 'Cuánto abarca la cámara. Más amplio se siente rápido; más cerrado, cinematográfico.',
    bloom: 'Resplandor',
    'bloom.desc': 'El neón y las bombillas brillan en el aire que los rodea.',
    filmGrain: 'Grano de película',
    'filmGrain.desc': 'Un toque de grano y viñeta, como una vieja cinta de seguridad del casino.',
    motionBlur: 'Desenfoque de movimiento',
    'motionBlur.desc': 'Difumina el movimiento rápido. Desactívalo si te marea.',
    lensEffects: 'Efectos de lente',
    'lensEffects.desc': 'Gotas de lluvia en la lente y destellos de los faros.',

    masterVolume: 'General',
    'masterVolume.desc': 'Todo a la vez.',
    musicVolume: 'Música',
    'musicVolume.desc': 'Jazz de salón, altavoces del casino y la radio del coche.',
    sfxVolume: 'Efectos',
    'sfxVolume.desc': 'Fichas, cartas, puertas, pasos, puñetazos.',
    ambienceVolume: 'Ambiente',
    'ambienceVolume.desc': 'La ciudad, la sala del casino, la tele del vecino.',
    voiceVolume: 'Voces',
    'voiceVolume.desc': 'Gente hablando: desconocidos, crupieres, tus amigos.',
    uiVolume: 'Interfaz',
    'uiVolume.desc': 'Clics de menú y toques de ficha como estos.',

    mouseSensitivity: 'Sensibilidad del ratón',
    'mouseSensitivity.desc': 'Cuánto gira la cámara por cada movimiento del ratón.',
    invertY: 'Invertir vista',
    'invertY.desc': 'Empuja hacia arriba para mirar abajo, como un avión.',
    touchStyle: 'Controles táctiles',
    'touchStyle.desc': 'Dos joysticks, o toca adonde quieras caminar.',
    'touchStyle.joysticks': 'Joysticks',
    'touchStyle.tap': 'Tocar para mover',
    'keys.title': 'Teclado',
    'keys.move': 'Caminar',
    'keys.sprint': 'Correr',
    'keys.jump': 'Saltar',
    'keys.crouch': 'Agacharse',
    'keys.interact': 'Interactuar',
    'keys.use': 'Usar',
    'keys.phone': 'Teléfono',
    'keys.pockets': 'Bolsillos',
    'keys.emote': 'Gestos',
    'keys.flop': 'Desplomarse',
    'keys.talk': 'Hablar',
    'keys.camera': 'Cambiar hombro',
    'keys.menu': 'Menú',

    swearFilter: 'Filtro de groserías',
    'swearFilter.desc': 'Pita el lenguaje fuerte de la gente, la radio y la tele.',
    blood: 'Sangre',
    'blood.desc': 'Sangre realista en peleas y accidentes.',
    subtitles: 'Subtítulos',
    'subtitles.desc': 'Muestra en texto lo que dice la gente.',
    npcVoices: 'Voces de desconocidos',
    'npcVoices.desc': 'Cómo te habla la gente de Reno.',
    'npcVoices.tts': 'Voces reales',
    'npcVoices.gibberish': 'Simlish',
    'npcVoices.text': 'Solo texto',

    micEnabled: 'Micrófono',
    'micEnabled.desc': 'Habla con tu voz real. Pide permiso la primera vez.',
    micMode: 'Modo de micrófono',
    'micMode.desc': 'Siempre escuchando, o solo mientras mantienes la tecla de hablar.',
    'micMode.open': 'Micro abierto',
    'micMode.push': 'Pulsar para hablar',
    voiceTalkToNpcs: 'Hablar con desconocidos',
    'voiceTalkToNpcs.desc': 'La gente de Reno oye y responde lo que dices.',
    realVoiceOut: 'Tu voz real',
    'realVoiceOut.desc': 'Los demás oyen tu voz de verdad saliendo de tu personaje.',
    nameTags: 'Etiquetas de nombre',
    'nameTags.desc': 'Nombres flotando sobre tus amigos en las salas en línea.',
    'voice.online': 'Las salas en línea llegarán en una próxima actualización; estas opciones quedan guardadas.',

    language: 'Idioma',
    'language.desc': 'Menús, teléfono, carteles legibles y subtítulos.',
    'language.en': 'English',
    'language.es': 'Español',

    textScale: 'Tamaño del texto',
    'textScale.desc': 'Escala los menús, el teléfono y los subtítulos.',
    reduceFlashing: 'Reducir destellos',
    'reduceFlashing.desc': 'Suaviza premios con luces estroboscópicas, sirenas y parpadeo de neón.',
    devOverlay: 'Indicador de rendimiento',
    'devOverlay.desc': 'Fotogramas y datos del render en la esquina (F3).',

    'load.loading': 'Cargando',
    'load.tip': 'Consejo de la casa',
    'load.free': 'Tirada gratis mientras esperas',
    'load.spin': 'Girar',
    'load.spinAgain': 'Otra vez',
    'load.win': '¡Premio! {n} créditos imaginarios',
    'load.lose': 'Casi.',
    'load.big': '¡PREMIO GORDO! No vale absolutamente nada.',
    'load.credits': 'Créditos: {n}',
    'paper.name': 'The Truckee Times',
    'paper.motto': 'El periódico más honesto de Reno desde el martes pasado',
    'paper.price': '50¢',
    'paper.edition': 'Última edición',
    'paper.weather': 'Clima: calor seco, noches frías, viento de la Sierra',

    'cred.kicker': 'Un juego de Loaded Dice Studios',
    'cred.design': 'Diseño de juego',
    'cred.direction': 'Dirección',
    'cred.code': 'Programación',
    'cred.art': 'Arte y modelado procedural',
    'cred.anim': 'Animación y físicas de rebote',
    'cred.audio': 'Música y sonido',
    'cred.writing': 'Guion',
    'cred.qa': 'Control de calidad',
    'cred.studio': 'Loaded Dice Studios',
    'cred.original': 'Todo el arte, modelos, sonidos y música son originales y generados por código.',
    'cred.virtual': 'Solo dinero virtual. No se puede ganar ni perder dinero real.',
    'cred.thirdParty': 'Hecho con',
    'cred.fonts': 'Tipografías',
    'cred.thanks': 'Gracias por jugar.',
    'cred.back': 'Volver a la máquina',
  },
});
