// Plain-words help for every page: what it is for, what each control does,
// and quick "how do I" answers. Used by the ❓ buttons, the Help page and the tour.

export const PAGE_HELP = {
  home: {
    title: '🏠 Home',
    what: 'Your dashboard. Shows your current cursor and the four big on/off switches.',
    items: [
      ['Change cursor', 'Jumps to 🖱️ Cursors to pick a different one.'],
      ['Customize', 'Jumps to 🎨 Customize to change colors, glow, size and animation.'],
      ['Random combo', 'Picks a random cursor, trail, click effect and typing sound for you.'],
      ['Custom cursor switch', 'Off = your normal Windows cursor comes back right away.'],
      ['Trails & clicks switch', 'Turns all the effects that follow your mouse on or off.'],
      ['Typing sounds switch', 'Turns the key sounds on or off everywhere.'],
      ['Voice control switch', 'Turns listening for "click", "click P" and so on on or off.'],
      ['Quick presets', 'One-click combos like Gaming Mode or Chill Mode.'],
      ['Hotkeys list', 'Keyboard shortcuts that work in every app, even when this window is closed.'],
    ],
  },
  cursors: {
    title: '🖱️ Cursors',
    what: 'All 100 built-in cursors plus the ones you make. Click one and it is on your whole PC instantly.',
    items: [
      ['Tabs at the top', 'Filter by type: Gaming, Weapons, Cute, Pixel, or ⭐ My Cursors.'],
      ['Search box', 'Type a name like "sword" or "cat".'],
      ['ANIM badge', 'That cursor moves by itself. Hover it to watch.'],
      ['My Cursors ✏️ / 🗑️', 'Edit or delete cursors you made in the Pixel Editor or uploaded.'],
    ],
  },
  customize: {
    title: '🎨 Customize',
    what: 'Changes how the current cursor looks. Everything applies live.',
    items: [
      ['Test area', 'Move your mouse into the box to try the look (it shows a still copy).'],
      ['Cursor size', 'Bigger or smaller. 32 is normal Windows size.'],
      ['Which cursors to replace', 'Normal arrow, the link hand, the text I-beam, loading, crosshair and help cursor. Turn off the ones you want to keep normal.'],
      ['Link badge', 'Puts a little ↗ bubble on the cursor over links so you still know it is clickable.'],
      ['Color: Original / Tint / Rainbow', 'Keep its colors, paint it one color, or make it cycle through the rainbow.'],
      ['Hue / Saturation / Brightness', 'Shift the colors, make them stronger or weaker, lighter or darker.'],
      ['Glow', 'Adds a glowing aura in any color.'],
      ['Outline', 'Adds a border so the cursor is easy to see on any background.'],
      ['Animation', 'Makes any cursor pulse, spin, bounce, wobble, swing, float, shake or flicker.'],
      ['Reset tweaks', 'Puts all the tweaks back to default (keeps your chosen cursor).'],
    ],
  },
  editor: {
    title: '✏️ Pixel Editor',
    what: 'Make your own cursor. Draw it pixel by pixel, or upload a picture or GIF.',
    items: [
      ['✏️ 🧽 🪣 💧 📏 ⬜', 'Pencil, eraser, fill bucket, color picker, line and rectangle.'],
      ['🎯 Hotspot', 'The exact pixel that does the clicking (the red box). Put it on the tip.'],
      ['Mirror', 'Draws both sides at once, good for symmetric shapes.'],
      ['Frames', 'Add frames to make it animated. Onion skin shows the last frame faintly.'],
      ['Speed', 'How fast the frames play.'],
      ['Start from a built-in cursor', 'Copies any of the 100 cursors so you can remix it.'],
      ['Upload image / GIF', 'Turns a PNG, JPG or GIF into a cursor. Click the picture to set the click point.'],
      ['Undo / Redo', 'Ctrl+Z and Ctrl+Y.'],
    ],
  },
  effects: {
    title: '✨ Effects',
    what: 'Things drawn around your mouse on your whole screen.',
    items: [
      ['Trail', 'What follows your mouse while it moves (sparkles, fire, rainbow...).'],
      ['Click effect', 'What pops out when you click (ripple, confetti, POW!...).'],
      ['When you stop moving', 'An effect that appears after your mouse sits still for a bit (zZz, hearts...).'],
      ['Length / Size / Amount', 'How long the trail lasts, how big, and how many bits.'],
      ['Low power mode', 'Fewer particles and slower backgrounds, good for laptops and games.'],
    ],
  },
  sounds: {
    title: '🔊 Sounds',
    what: 'A sound every time you press a key, in every app (or only the apps you pick in 🎯 Apps).',
    items: [
      ['Sound packs', 'Click one to use it. ▶ plays a preview.'],
      ['Volume / Pitch variety', 'How loud, and how much each press sounds slightly different.'],
      ['Key release sound', 'A small extra sound when you let go of a key.'],
      ['Mouse click sounds', 'Plays a sound when you click too.'],
      ['Your own sounds', 'Add your own MP3/WAV files. Add several key sounds and it picks a random one each press.'],
    ],
  },
  music: {
    title: '🎵 Music',
    what: 'Music that keeps playing even when this window is closed.',
    items: [
      ['⏮ ▶ ⏭', 'Previous song, play/pause, next song.'],
      ['Shuffle / Repeat', 'Random order, repeat everything, repeat one song, or stop at the end.'],
      ['Built-in songs', 'Original songs CursorVerse makes live: lofi, 8-bit, synthwave and ambient/rain.'],
      ['My music', 'Add your own songs (MP3, WAV, OGG, M4A, FLAC).'],
      ['Play music when CursorVerse starts', 'Starts music automatically when the app opens.'],
    ],
  },
  browser: {
    title: '🌐 Browser',
    what: 'A web browser inside CursorVerse with your own background on the home page.',
    items: [
      ['Address bar', 'Type a website (like youtube.com) or anything to search.'],
      ['Tabs', '+ opens a new tab. Middle-click a tab or press Ctrl+W to close it. Ctrl+Shift+T brings back the last one.'],
      ['☆ / ★', 'Adds or removes the page from the speed dial tiles on the home page.'],
      ['🛡️ number', 'How many ads and trackers were blocked.'],
      ['⚙', 'Search engine, ad blocker on/off, reopen tabs, and History.'],
      ['Shortcuts', 'Ctrl+T new tab, Ctrl+L address bar, F5 reload, Alt+← back, Ctrl+H history, Ctrl+D speed dial.'],
    ],
  },
  backgrounds: {
    title: '🌌 Backgrounds',
    what: 'The background behind this app, and behind the browser home page.',
    items: [
      ['App / Browser', 'Pick which background you are changing. The browser can use the same one as the app.'],
      ['Animated', 'Moving backgrounds made by CursorVerse. Hover a card to preview it.'],
      ['Your own file', 'Any picture, GIF or video from your PC.'],
      ['Blur / Dim', 'Makes busy pictures easier to read text on.'],
    ],
  },
  apps: {
    title: '🎯 Apps',
    what: 'Choose where your cursor, effects and typing sounds work: everywhere, or only in the apps you pick.',
    items: [
      ['Everywhere / Only the apps I pick', 'With "only", your normal cursor comes back when you switch to any other app.'],
      ['Pick by clicking it', 'Press it, then click the app you want within 15 seconds.'],
      ['Refresh open apps', 'Lists the apps open right now so you can add one.'],
      ['Popular apps / type an .exe', 'Quick add for common apps, or type the program name.'],
    ],
  },
  voice: {
    title: '🎤 Voice',
    what: 'Control your PC with your voice: say "click" to click, "click P" to press P, and more.',
    items: [
      ['Status + "heard" list', 'Shows what it heard and exactly what it did about it, like "normal talking, ignored" or "too unsure".'],
      ['How it listens', 'Always listening, only while you hold a key (best if you talk a lot), or after "hey cursor".'],
      ['"Did you say ___?"', 'When it asks, say "yes" to press it or "no" to cancel. Pick when it should ask.'],
      ['How fast it reacts', 'A wait after it hears you, from 0.1 ms to minutes. Type any number and pick ms, seconds or minutes.'],
      ['Letters', '"click P", "click papa" (pilot words), or both. Pilot words are easier for the mic to tell apart.'],
      ['Stop random triggers', 'Ignore normal talking, pause while another app (Discord, voice typing) uses the mic, and need "click" before your own commands.'],
      ['How sure it must be', 'Higher = fewer mistakes but you may need to repeat. Lower = reacts more easily.'],
      ['Wait after you stop talking', 'Lower = faster, but it might cut you off mid-word.'],
      ['My own commands', 'Make a word type text, press keys, or click. You say "click" + your word.'],
      ['Where voice works', 'Everywhere, or only in the apps you pick.'],
    ],
  },
  presets: {
    title: '💾 Presets',
    what: 'Save your whole setup (cursor, effects, sounds, music, background) and switch with one click.',
    items: [
      ['Built in', 'Ready-made combos: Gaming, Chill, Fantasy, Retro, Cute and Chaos.'],
      ['Save current as preset', 'Saves exactly what you have on right now with a name and emoji.'],
      ['Random combo', 'Surprise mix of cursor, trail, click effect and sounds.'],
    ],
  },
  settings: {
    title: '⚙️ Settings',
    what: 'Theme, hotkeys, startup, updates and fix-it buttons.',
    items: [
      ['Theme / Accent color', 'Dark Neon, Glassy or Pixel Retro, plus your own highlight color.'],
      ['Hotkeys', 'Click a box and press a new combo. They work in every app.'],
      ['Start with Windows', 'CursorVerse starts when your PC does, hidden in the tray.'],
      ['Closing the window keeps it running', 'X hides it by the clock so your cursor and music keep going. Right-click the tray icon → Quit to fully close it.'],
      ['Updates', 'Check for a new version and install it with one click. Your settings stay.'],
      ['Put my normal cursor back', 'Turns the custom cursor off and restores Windows\' cursor.'],
      ['Reset everything', 'All settings back to default. Your own cursors and files stay.'],
    ],
  },
};

export const HOW_TO = [
  ['How do I change my cursor?', '🖱️ Cursors → click any cursor. Done.'],
  ['How do I get my normal Windows cursor back?', 'Turn off the 🖱️ Cursor pill at the top, or ⚙️ Settings → Put my normal cursor back. From the tray: right-click the icon → Put normal cursor back.'],
  ['How do I fully close CursorVerse?', 'Right-click its icon by the clock (click the ^ arrow if you do not see it) → Quit.'],
  ['How do I update CursorVerse?', '⚙️ Settings → Updates → Update now. It downloads, restarts, and keeps all your stuff.'],
  ['How do I make voice press a key?', '🎤 Voice → say "click" and the letter, like "click P" or "click papa". Say "yes" if it asks "Did you say P?".'],
  ['Voice keeps pressing stuff while I talk to people!', '🎤 Voice → 🛡️ Stop random triggers: keep "Ignore normal talking" and "Pause while another app uses the mic" on. Still happening? Switch "How it listens" to 🔘 Hold a key to talk.'],
  ['Voice heard me right but did nothing?', 'Look at the list under 📡 Status. It says why: too unsure, another app using the mic, voice off for this app, or it is waiting for "yes".'],
  ['How do I make my own voice command?', '🎤 Voice → My own commands → ➕ Add command. Type the word, pick what it does, then say "click" + your word.'],
  ['How do I make my own cursor?', '✏️ Pixel Editor → draw it (or Upload image / GIF) → ⭐ Save & use it.'],
  ['How do I make it only work in one app?', '🎯 Apps → Only the apps I pick → add your app.'],
  ['How do I turn off typing sounds?', 'Click the 🔊 Sounds pill at the top, or press Ctrl+Alt+S anywhere.'],
  ['How do I add my own music?', '🎵 Music → ⭐ My music → ➕ Add songs.'],
  ['How do I change the background?', '🌌 Backgrounds → pick an animated one, or Choose file for your own picture or video.'],
];

// Steps for the guided tour. target = CSS selector to point at.
export const TOUR = [
  { target: null, title: 'Welcome to CursorVerse 👋', text: 'Quick tour so you know where everything is. Takes about a minute. You can skip any time.' },
  { target: '#quick', title: 'Quick switches ⚡', text: 'Turn the cursor, effects, sounds and voice on or off, control music, and 🎲 try a random combo. Always here at the top.' },
  { target: '#side button[data-id="cursors"]', title: 'Pick a cursor 🖱️', text: '100 cursors. Click one and it is on your whole PC instantly.' },
  { target: '#side button[data-id="customize"]', title: 'Customize 🎨', text: 'Change colors, glow, outline, size, and make any cursor spin or bounce.' },
  { target: '#side button[data-id="editor"]', title: 'Make your own ✏️', text: 'Draw a cursor pixel by pixel, or turn a picture or GIF into one.' },
  { target: '#side button[data-id="effects"]', title: 'Effects ✨', text: 'Trails behind your mouse, effects when you click, and something cute when you stop moving.' },
  { target: '#side button[data-id="sounds"]', title: 'Typing sounds 🔊', text: '20 sound packs, or add your own sounds.' },
  { target: '#side button[data-id="voice"]', title: 'Voice control 🎤', text: 'Say "click" to click, "click P" to press P. The 🛡️ Stop random triggers settings keep it from reacting when you talk to people.' },
  { target: '#side button[data-id="apps"]', title: 'Where it works 🎯', text: 'Everywhere, or only in the apps you pick.' },
  { target: '#side button[data-id="presets"]', title: 'Presets 💾', text: 'Save your whole setup and switch with one click.' },
  { target: '#side button[data-id="settings"]', title: 'Settings & updates ⚙️', text: 'Themes, hotkeys, start with Windows, and one-click updates.' },
  { target: '#side button[data-id="help"]', title: 'Stuck? ❓', text: 'The Help page answers "how do I...?" questions, and every page has a ❓ button that explains what each thing does.' },
];
