// Player-facing strings for the DMV photo booth creator (EN + ES).
// Parameter / option labels come from the character module's own namespace (character.p.*,
// character.o.*); this file only holds the creator's form chrome and the clerk's lines.

import { i18n } from '../core/i18n.js';

i18n.register('creator', {
  en: {
    dept: 'Department of Motor Vehicles',
    state: 'State of Nevada · Washoe County',
    formTitle: 'Application for Driver License',
    formNo: 'Form DLV-21 (rev. 1987)',
    applicant: 'Applicant',
    first: 'First name',
    last: 'Last name',
    age: 'Age',
    ageNote: 'Must be 21 or older to enter a casino.',
    randomName: 'Random name',
    randomAll: 'Shuffle everything',
    randomSection: 'Shuffle',
    secBody: 'Body',
    secFace: 'Face',
    secEyes: 'Eyes & brows',
    secHair: 'Hair',
    secBeard: 'Facial hair',
    secSkin: 'Skin details',
    secClothes: 'Clothes',
    secVoice: 'Voice',
    voiceSystem: 'Voice on file',
    voiceDefault: 'Default voice',
    voiceNone: 'No voices on this device',
    voicePreview: 'Say something',
    voiceLine: "Hi, I'm here for my license photo.",
    yes: 'Yes',
    no: 'No',
    takePhoto: 'Take photo',
    signHere: 'Sign here',
    office: 'Office use only',
    nowServing: 'NOW SERVING',
    takeNumber: 'TAKE A NUMBER',
    dontSmile: "Don't smile.",
    lookHere: 'Look at the dot.',
    hold: 'Hold still…',
    next: 'Next!',
    dragHint: 'Drag to turn · pinch or scroll to zoom',
    faceZoom: 'Face',
    bodyZoom: 'Full',
    license: 'Driver License',
    lic_dl: 'DL',
    lic_dob: 'DOB',
    lic_exp: 'EXP',
    lic_iss: 'ISS',
    lic_class: 'CLASS',
    lic_sex: 'SEX',
    lic_hgt: 'HGT',
    lic_eyes: 'EYES',
    lic_hair: 'HAIR',
    lic_addr: '4TH ST, RENO NV 89501',
    lic_donor: 'DONOR',
    lic_state: 'SILVER STATE',
    soonTitle: 'Reno is still being built',
    soonBody: 'Your license is in your wallet. The city opens its doors soon.',
    soonBack: 'Back to the counter',
    working: 'Processing…',
  },
  es: {
    dept: 'Departamento de Vehículos Motorizados',
    state: 'Estado de Nevada · Condado de Washoe',
    formTitle: 'Solicitud de licencia de conducir',
    formNo: 'Formulario DLV-21 (rev. 1987)',
    applicant: 'Solicitante',
    first: 'Nombre',
    last: 'Apellido',
    age: 'Edad',
    ageNote: 'Debes tener 21 años o más para entrar a un casino.',
    randomName: 'Nombre al azar',
    randomAll: 'Barajar todo',
    randomSection: 'Barajar',
    secBody: 'Cuerpo',
    secFace: 'Cara',
    secEyes: 'Ojos y cejas',
    secHair: 'Cabello',
    secBeard: 'Vello facial',
    secSkin: 'Detalles de la piel',
    secClothes: 'Ropa',
    secVoice: 'Voz',
    voiceSystem: 'Voz registrada',
    voiceDefault: 'Voz predeterminada',
    voiceNone: 'No hay voces en este dispositivo',
    voicePreview: 'Decir algo',
    voiceLine: 'Hola, vengo por la foto de mi licencia.',
    yes: 'Sí',
    no: 'No',
    takePhoto: 'Tomar foto',
    signHere: 'Firme aquí',
    office: 'Solo para uso oficial',
    nowServing: 'ATENDIENDO',
    takeNumber: 'TOME UN NÚMERO',
    dontSmile: 'No sonría.',
    lookHere: 'Mire el punto.',
    hold: 'No se mueva…',
    next: '¡Siguiente!',
    dragHint: 'Arrastra para girar · pellizca o rueda para acercar',
    faceZoom: 'Cara',
    bodyZoom: 'Entero',
    license: 'Licencia de conducir',
    lic_dl: 'DL',
    lic_dob: 'NAC',
    lic_exp: 'VENCE',
    lic_iss: 'EXP',
    lic_class: 'CLASE',
    lic_sex: 'SEXO',
    lic_hgt: 'ALT',
    lic_eyes: 'OJOS',
    lic_hair: 'PELO',
    lic_addr: '4TH ST, RENO NV 89501',
    lic_donor: 'DONANTE',
    lic_state: 'ESTADO DE PLATA',
    soonTitle: 'Reno aún está en construcción',
    soonBody: 'Tu licencia ya está en tu cartera. La ciudad abre sus puertas pronto.',
    soonBack: 'Volver al mostrador',
    working: 'Procesando…',
  },
});
