// Player-facing text for the life systems (needs, rent, phone, pockets) in English and Spanish.
// Registered under the 'life' namespace; read with t('life.<key>').

import { i18n } from '../core/i18n.js';

i18n.register('life', {
  en: {
    // Rent / clerk
    'clerk.name': 'Night clerk',
    'clerk.greet': 'Room {room}. It\'s forty-five a night, cash. You staying?',
    'clerk.greetPaid': 'You\'re good through {when}. Need anything else?',
    'clerk.pay': 'Pay $45 for tonight',
    'clerk.notYet': 'Not yet',
    'clerk.bye': 'Never mind',
    'clerk.thanks': 'Thanks. Checkout\'s eleven. Don\'t make me come knocking.',
    'clerk.broke': 'That\'s not forty-five. Come back when you have it.',
    'clerk.later': 'Clock\'s ticking, friend.',
    'clerk.knock': 'Hey! Room {room}! Rent was due at eleven. Pay up or pack up.',
    // Phone
    'phone.swipe': 'Swipe up to unlock',
    'phone.dead': '',
    'phone.lowBattery': 'Battery low',
    'phone.clock': 'Clock',
    'phone.messages': 'Messages',
    'phone.wallet': 'Wallet',
    'phone.maps': 'Maps',
    'phone.camera': 'Camera',
    'phone.settings': 'Settings',
    'phone.alarm': 'Alarm',
    'phone.alarmOn': 'Alarm set for {time}',
    'phone.alarmOff': 'No alarm',
    'phone.alarmHint': 'Tap + / − to change the hour. Toggle to arm it.',
    'phone.wake': 'Wake up',
    'phone.snooze': 'Snooze',
    'phone.dismiss': 'Stop',
    'phone.unknown': 'Unknown',
    'phone.noMessages': 'No messages yet',
    'phone.call': 'Call',
    'phone.calling': 'Calling…',
    'phone.notInService': 'The number you have dialed is not in service. Please check the number and try again.',
    'phone.endCall': 'End',
    'phone.napkinNumber': 'From a bar napkin',
    'phone.cash': 'Cash',
    'phone.bank': 'Bank',
    'phone.chips': 'Casino chips',
    'phone.idCard': 'Driver license',
    'phone.youAreHere': 'You',
    'phone.saved': 'Photo saved',
    'phone.shutter': 'Take photo',
    'phone.back': 'Back',
    'phone.home': 'Home',
    'phone.sim': 'No SIM · Emergency calls only',
    'phone.carrier': 'SilverLine',
    'msg.carrier': 'Your bill of $38.12 is past due. Pay now to avoid service interruption.',
    'msg.spam': 'PAYDAY NOW: You are PRE-APPROVED for $500 cash TODAY! No credit check. Reply YES',
    'msg.yesterday': 'Yesterday',
    'msg.mon': 'Mon',
    // Map labels
    'map.4th': 'E 4th St',
    'map.virginia': 'N Virginia St',
    'map.commercial': 'Commercial Row',
    'map.5th': 'W 5th St',
    'map.lake': 'Lake St',
    'map.starlite': 'Starlite Motel',
    'map.eldorado': 'Eldorado',
    'map.legacy': 'Silver Legacy',
    'map.circus': 'Circus Circus',
    'map.arch': 'Reno Arch',
    'map.trench': 'Railroad',
    // Pockets
    'pockets.title': 'Pockets',
    'pockets.hint': 'Pick something to look closer',
    'pockets.close': 'Put it all back',
    'item.wallet': 'Wallet',
    'item.wallet.desc': 'Cracked fake leather. Your license and whatever cash you have left.',
    'item.cash': 'Cash',
    'item.cash.desc': '{amount}, crumpled.',
    'item.phone': 'Phone',
    'item.phone.desc': 'A budget Android with a spider-web crack across the screen.',
    'item.keycard': 'Room key',
    'item.keycard.desc': 'Starlite Motel key card. Room {room}.',
    'item.napkin': 'Napkin',
    'item.napkin.desc': 'Written in eyeliner: “{name} — {number}”. You don\'t remember who gave it to you.',
    'item.receipt': 'Receipt',
    'item.receipt.desc': 'Eldorado bar, 2:47 AM. Four whiskey sours, two tequila shots. Tip: $0.',
    'item.id': 'Driver license',
    // Needs / death
    'death.starved': 'Starvation',
    'death.thirst': 'Dehydration',
    'death.exhaustion': 'Collapsed from exhaustion',
    'death.exposure': 'Exposure',
    'death.health': 'Poor health',
  },
  es: {
    'clerk.name': 'Recepcionista',
    'clerk.greet': 'Habitación {room}. Son cuarenta y cinco la noche, en efectivo. ¿Se queda?',
    'clerk.greetPaid': 'Está pagado hasta {when}. ¿Algo más?',
    'clerk.pay': 'Pagar $45 por esta noche',
    'clerk.notYet': 'Todavía no',
    'clerk.bye': 'Nada, olvídelo',
    'clerk.thanks': 'Gracias. La salida es a las once. No me haga ir a tocar la puerta.',
    'clerk.broke': 'Eso no son cuarenta y cinco. Vuelva cuando los tenga.',
    'clerk.later': 'El reloj corre, amigo.',
    'clerk.knock': '¡Oiga! ¡Habitación {room}! La renta vencía a las once. Pague o váyase.',
    'phone.swipe': 'Desliza hacia arriba para desbloquear',
    'phone.lowBattery': 'Batería baja',
    'phone.clock': 'Reloj',
    'phone.messages': 'Mensajes',
    'phone.wallet': 'Cartera',
    'phone.maps': 'Mapas',
    'phone.camera': 'Cámara',
    'phone.settings': 'Ajustes',
    'phone.alarm': 'Alarma',
    'phone.alarmOn': 'Alarma a las {time}',
    'phone.alarmOff': 'Sin alarma',
    'phone.alarmHint': 'Toca + / − para cambiar la hora. Actívala con el interruptor.',
    'phone.wake': 'Despierta',
    'phone.snooze': 'Posponer',
    'phone.dismiss': 'Detener',
    'phone.unknown': 'Desconocido',
    'phone.noMessages': 'Aún no hay mensajes',
    'phone.call': 'Llamar',
    'phone.calling': 'Llamando…',
    'phone.notInService': 'El número que usted marcó no está en servicio. Verifique el número e intente de nuevo.',
    'phone.endCall': 'Colgar',
    'phone.napkinNumber': 'De una servilleta de bar',
    'phone.cash': 'Efectivo',
    'phone.bank': 'Banco',
    'phone.chips': 'Fichas de casino',
    'phone.idCard': 'Licencia de conducir',
    'phone.youAreHere': 'Tú',
    'phone.saved': 'Foto guardada',
    'phone.shutter': 'Tomar foto',
    'phone.back': 'Atrás',
    'phone.home': 'Inicio',
    'phone.sim': 'Sin SIM · Solo emergencias',
    'phone.carrier': 'SilverLine',
    'msg.carrier': 'Su factura de $38.12 está vencida. Pague ahora para evitar la suspensión del servicio.',
    'msg.spam': 'PAYDAY NOW: ¡Está PRE-APROBADO para $500 en efectivo HOY! Sin revisión de crédito. Responda SÍ',
    'msg.yesterday': 'Ayer',
    'msg.mon': 'lun',
    'map.4th': 'E 4th St',
    'map.virginia': 'N Virginia St',
    'map.commercial': 'Commercial Row',
    'map.5th': 'W 5th St',
    'map.lake': 'Lake St',
    'map.starlite': 'Motel Starlite',
    'map.eldorado': 'Eldorado',
    'map.legacy': 'Silver Legacy',
    'map.circus': 'Circus Circus',
    'map.arch': 'Arco de Reno',
    'map.trench': 'Ferrocarril',
    'pockets.title': 'Bolsillos',
    'pockets.hint': 'Elige algo para verlo de cerca',
    'pockets.close': 'Guardar todo',
    'item.wallet': 'Cartera',
    'item.wallet.desc': 'Cuero falso agrietado. Tu licencia y el efectivo que te queda.',
    'item.cash': 'Efectivo',
    'item.cash.desc': '{amount}, arrugados.',
    'item.phone': 'Teléfono',
    'item.phone.desc': 'Un Android barato con la pantalla rota como telaraña.',
    'item.keycard': 'Llave de la habitación',
    'item.keycard.desc': 'Tarjeta del Motel Starlite. Habitación {room}.',
    'item.napkin': 'Servilleta',
    'item.napkin.desc': 'Escrito con delineador: «{name} — {number}». No recuerdas quién te la dio.',
    'item.receipt': 'Recibo',
    'item.receipt.desc': 'Bar del Eldorado, 2:47 AM. Cuatro whiskey sours, dos tequilas. Propina: $0.',
    'item.id': 'Licencia de conducir',
    'death.starved': 'Inanición',
    'death.thirst': 'Deshidratación',
    'death.exhaustion': 'Colapso por agotamiento',
    'death.exposure': 'Exposición',
    'death.health': 'Mala salud',
  },
});
