// Item database and crafting recipes (backyard size AND germ size).

export const ITEMS = {
  // ---- backyard materials
  pebble: { name: 'Pebble', icon: '⚪', type: 'material', desc: 'A small round stone. At your size, a boulder you can carry.' },
  fiber: { name: 'Plant Fiber', icon: '🧵', type: 'material', desc: 'Tough strands pulled from dry grass. Holds everything together.' },
  twig: { name: 'Twig', icon: '🥢', type: 'material', desc: 'A splinter of wood. Basically a log to you.' },
  grass_plank: { name: 'Grass Plank', icon: '🌾', type: 'material', desc: 'A cut section of grass blade. Light and surprisingly strong.' },
  stone: { name: 'Stone Chunk', icon: '🪨', type: 'material', desc: 'Chipped off a big rock with a pickaxe.' },
  quartz: { name: 'Quartzite', icon: '💎', type: 'material', desc: 'A glittering crystal shard. Sharp.' },
  leaf: { name: 'Leaf', icon: '🍃', type: 'material', desc: 'A dry leaf. Makes great shade.' },
  clover: { name: 'Clover Leaf', icon: '🍀', type: 'material', desc: 'Soft and medicinal-ish.' },
  sap: { name: 'Sap', icon: '🍯', type: 'material', desc: 'Sticky, flammable plant sap.' },
  thorn: { name: 'Rose Thorn', icon: '🥀', type: 'material', desc: 'Wickedly sharp. Handle with care.' },
  silk: { name: 'Spider Silk', icon: '🕸️', type: 'material', desc: 'Stronger than steel, at any size.' },
  chitin: { name: 'Bug Chitin', icon: '🪲', type: 'material', desc: 'Armour plating from a defeated bug.' },
  ant_part: { name: 'Ant Mandible', icon: '🐜', type: 'material', desc: 'Pincers that could snap a twig.' },
  mosquito_needle: { name: 'Mosquito Needle', icon: '💉', type: 'material', desc: 'A perfect, deadly point.' },
  beetle_horn: { name: 'Beetle Horn', icon: '🦏', type: 'material', desc: 'Heavy. Very heavy.' },
  acorn: { name: 'Acorn Cap', icon: '🌰', type: 'material', desc: 'A natural helmet.' },
  venom: { name: 'Venom Sac', icon: '🧪', type: 'material', desc: 'Handle with extreme care.' },
  // ---- food
  dew: { name: 'Dew Drop', icon: '💧', type: 'food', heal: 20, desc: 'Fresh water. At your size, a whole bottle.' },
  berry: { name: 'Berry Chunk', icon: '🫐', type: 'food', heal: 35, desc: 'Sweet, juicy and the size of your head.' },
  mushroom: { name: 'Mushroom Chunk', icon: '🍄', type: 'food', heal: 15, desc: 'Probably edible.' },
  honeydew: { name: 'Aphid Honeydew', icon: '🍯', type: 'food', heal: 50, desc: 'Sugary goo. Don\'t ask where it comes from.' },
  crumb: { name: 'Cracker Crumb', icon: '🍪', type: 'food', heal: 25, desc: 'Found on the sidewalk. Still crunchy.' },
  bandage: { name: 'Clover Bandage', icon: '🩹', type: 'food', heal: 60, desc: 'Silk-wrapped clover. Heals a lot.' },
  // ---- tools & weapons (backyard)
  axe: { name: 'Pebble Axe', icon: '🪓', type: 'tool', tool: 'axe', dmg: 9, reach: 1.9, speed: 0.55, dur: 120, desc: 'Cuts grass, stems, webs and thorns.' },
  pickaxe: { name: 'Pebble Pickaxe', icon: '⛏️', type: 'tool', tool: 'pickaxe', dmg: 8, reach: 1.9, speed: 0.6, dur: 120, desc: 'Mines stone and quartz from big rocks.' },
  spear: { name: 'Grass Spear', icon: '🔱', type: 'weapon', dmg: 14, reach: 2.8, speed: 0.5, dur: 90, desc: 'Keep bugs at a distance.' },
  club: { name: 'Pebble Club', icon: '🏏', type: 'weapon', dmg: 19, reach: 2.0, speed: 0.75, dur: 110, desc: 'Big stone on a stick. Classic.' },
  thorn_sword: { name: 'Thorn Sword', icon: '🗡️', type: 'weapon', dmg: 24, reach: 2.3, speed: 0.45, dur: 140, desc: 'A rose thorn blade. Fast and sharp.' },
  rapier: { name: 'Mosquito Rapier', icon: '🤺', type: 'weapon', dmg: 30, reach: 2.6, speed: 0.35, dur: 160, desc: 'Needle-point fencing blade.' },
  hammer: { name: 'Beetle Horn Hammer', icon: '🔨', type: 'weapon', dmg: 42, reach: 2.2, speed: 0.95, dur: 200, desc: 'Slow. Devastating.' },
  bow: { name: 'Twig Bow', icon: '🏹', type: 'weapon', ranged: 'arrow', dmg: 20, speed: 0.6, dur: 150, desc: 'Shoots thorn arrows. Needs arrows in your backpack.' },
  arrow: { name: 'Thorn Arrow', icon: '➶', type: 'ammo', desc: 'Ammo for the Twig Bow.' },
  torch: { name: 'Sap Torch', icon: '🔦', type: 'tool', tool: 'torch', dmg: 6, reach: 1.8, speed: 0.5, dur: 300, light: true, desc: 'Lights up dark places. Spiders hate it.' },
  parasol: { name: 'Leaf Parasol', icon: '☂️', type: 'tool', tool: 'parasol', dmg: 2, reach: 1.5, speed: 0.5, dur: 400, shade: true, desc: 'Hold it to stay out of the sun.' },
  helmet: { name: 'Acorn Helmet', icon: '⛑️', type: 'armor', armor: 0.15, desc: 'Reduces damage by 15%. Press F to wear.' },
  ant_armor: { name: 'Ant Chitin Armor', icon: '🛡️', type: 'armor', armor: 0.3, desc: 'Reduces damage by 30%. Press F to wear.' },
  // ---- buildables
  wall: { name: 'Grass Wall', icon: '🧱', type: 'build', build: 'wall', desc: 'Place with left click. B to cancel.' },
  floor: { name: 'Grass Floor', icon: '🟫', type: 'build', build: 'floor', desc: 'A platform to stand on.' },
  campfire: { name: 'Campfire', icon: '🔥', type: 'build', build: 'campfire', desc: 'Heals you when you rest near it. Scares bugs.' },
  workbench: { name: 'Workbench', icon: '🛠️', type: 'build', build: 'workbench', desc: 'Stand near it to craft advanced gear.' },
  lean_to: { name: 'Lean-To Shelter', icon: '⛺', type: 'build', build: 'lean_to', desc: 'Shade + a respawn point.' },
  ladder: { name: 'Grass Ladder', icon: '🪜', type: 'build', build: 'ladder', desc: 'Climb up tall things.' },
  dew_collector: { name: 'Dew Collector', icon: '🫗', type: 'build', build: 'dew_collector', desc: 'Collects a dew drop every minute.' },
  // ---- germ size
  cellulose: { name: 'Cellulose Strand', icon: '🧬', type: 'material', micro: true, desc: 'A strand from a plant cell wall. Tough fibre, microscopic.' },
  diatom_glass: { name: 'Diatom Glass', icon: '🔷', type: 'material', micro: true, desc: 'The glass shell of a diatom. Razor sharp.' },
  protein: { name: 'Protein Crystal', icon: '🔺', type: 'material', micro: true, desc: 'Crystallised protein from a defeated microbe.' },
  lipid: { name: 'Lipid Droplet', icon: '🫧', type: 'material', micro: true, desc: 'Fatty bubble. Makes membranes.' },
  flagellum: { name: 'Flagellum', icon: '〰️', type: 'material', micro: true, desc: 'A bacterium\'s tail. Whip-like.' },
  atp: { name: 'ATP Spark', icon: '⚡', type: 'food', heal: 30, micro: true, desc: 'Pure cellular energy. Restores health.' },
  macro_shard: { name: 'Macro Shard', icon: '✴️', type: 'key', desc: 'A glowing fragment of whatever shrank you. Collect 3.' },
  diatom_blade: { name: 'Diatom Glass Blade', icon: '🔪', type: 'weapon', dmg: 22, reach: 2.4, speed: 0.4, dur: 150, micro: true, desc: 'Microscopic glass sword.' },
  whip: { name: 'Flagellum Whip', icon: '➰', type: 'weapon', dmg: 17, reach: 3.8, speed: 0.45, dur: 150, micro: true, desc: 'Long reach, snappy.' },
  blaster: { name: 'Enzyme Blaster', icon: '🔫', type: 'weapon', ranged: 'enzyme', dmg: 18, speed: 0.35, dur: 200, micro: true, desc: 'Shoots digestive enzyme bolts. No ammo needed.' },
  membrane: { name: 'Lipid Membrane Armor', icon: '🫧', type: 'armor', armor: 0.35, micro: true, desc: 'A bubble of armour. Reduces damage by 35%.' },
};

// req: materials; needs: 'workbench' | 'outside' | 'micro'
export const RECIPES = [
  { id: 'axe', cat: 'Tools', req: { pebble: 3, fiber: 3 }, needs: 'outside' },
  { id: 'pickaxe', cat: 'Tools', req: { pebble: 3, grass_plank: 2, fiber: 3 }, needs: 'outside' },
  { id: 'torch', cat: 'Tools', req: { twig: 1, sap: 1, fiber: 1 }, needs: 'outside' },
  { id: 'parasol', cat: 'Tools', req: { leaf: 3, twig: 1, fiber: 2 }, needs: 'outside' },
  { id: 'spear', cat: 'Weapons', req: { grass_plank: 3, pebble: 1, fiber: 2 }, needs: 'outside' },
  { id: 'club', cat: 'Weapons', req: { twig: 1, pebble: 4, fiber: 2 }, needs: 'outside' },
  { id: 'thorn_sword', cat: 'Weapons', req: { thorn: 1, grass_plank: 2, fiber: 3 }, needs: 'outside' },
  { id: 'bow', cat: 'Weapons', req: { twig: 3, silk: 3 }, needs: 'workbench' },
  { id: 'arrow', cat: 'Weapons', req: { thorn: 1, twig: 1, fiber: 1 }, needs: 'outside', count: 5 },
  { id: 'rapier', cat: 'Weapons', req: { mosquito_needle: 1, grass_plank: 1, silk: 2 }, needs: 'workbench' },
  { id: 'hammer', cat: 'Weapons', req: { beetle_horn: 1, twig: 2, silk: 2 }, needs: 'workbench' },
  { id: 'helmet', cat: 'Survival', req: { acorn: 1, fiber: 2 }, needs: 'outside' },
  { id: 'ant_armor', cat: 'Survival', req: { chitin: 4, silk: 2 }, needs: 'workbench' },
  { id: 'bandage', cat: 'Survival', req: { clover: 1, silk: 1 }, needs: 'outside' },
  { id: 'wall', cat: 'Build', req: { grass_plank: 3 }, needs: 'outside' },
  { id: 'floor', cat: 'Build', req: { grass_plank: 2 }, needs: 'outside' },
  { id: 'workbench', cat: 'Build', req: { grass_plank: 4, pebble: 2 }, needs: 'outside' },
  { id: 'campfire', cat: 'Build', req: { pebble: 4, twig: 3, sap: 1 }, needs: 'outside' },
  { id: 'lean_to', cat: 'Build', req: { grass_plank: 4, leaf: 4, fiber: 2 }, needs: 'outside' },
  { id: 'ladder', cat: 'Build', req: { grass_plank: 3, fiber: 3 }, needs: 'outside' },
  { id: 'dew_collector', cat: 'Build', req: { leaf: 3, twig: 2, fiber: 2 }, needs: 'outside' },
  { id: 'diatom_blade', cat: 'Germ', req: { diatom_glass: 2, cellulose: 2 }, needs: 'micro' },
  { id: 'whip', cat: 'Germ', req: { flagellum: 2, protein: 1 }, needs: 'micro' },
  { id: 'blaster', cat: 'Germ', req: { protein: 3, lipid: 2, diatom_glass: 1 }, needs: 'micro' },
  { id: 'membrane', cat: 'Germ', req: { lipid: 4, cellulose: 2 }, needs: 'micro' },
];

export function item(id) { return ITEMS[id] || { name: id, icon: '❔', type: 'material', desc: '' }; }
